### PR TITLE
Switch View on Dash to use peepr

### LINKED ISSUE #953: View On Dash is missing "like"/heart button
Possibly same cause as #831 -- I haven't been active on tumblr for a while, and just noticed this. Screenshot attached should illustrate the issue -- this is with no other XKit extensions enabled but View On Dash.

Tested on Firefox and Chrome, same result.

view on dash issue

### PR DESCRIPTION
**Pull request by ThePsionic**
This switches View on Dash to use peepr instead of whatever was there before, cleaning up a lot of useless and messy legacy code.

However, I'm not completely sure this is the way to do it. View on Dash had its own interface, with the only difference being the ability to filter post types (which can probably be added at a later date) and the like buttons not showing up in the old version. This is why I don't want this PR pulled immediately, but rather hear opinions from both devs and users. I'm especially tagging @SophiaNOTLoren and @heytherenikita since they expressed interest in #953.

Fixes #953 if pulled.

### CODE REVIEW

**Comment by blackjackkent** [comment]
I definitely like this change personally for my own use and I do like the idea of being able to phase out the old messy code from VoD. Perhaps a wholesale wipeout of the existing functionality without warning isn't ideal, though; you know people are going to make noise about it. (Some people really dislike the sidebar from what I've heard.)

Then again I might be overestimating people's attachment to VoD as it currently stands. Possibly we can add this as a toggle and see how people react to it first?

**Comment by nightpool** [comment]
@BlackjackKent Maybe a survey distributed through View On Dash or as a news
item?

**Comment by nightpool** [comment]
Feel like toggle isn't going to get a lot of responses. Ideal would be
usage analytics but getting those would be pretty hard given our current
capabilities.

**Comment by blackjackkent** [comment]
@nightpool That could work too. IDK. Mostly I'm just reflecting that a lot of the flak Tumblr gets is for just dropping in UI changes without warning. Survey might be a good idea though, at least to gauge how much use the feature gets.

**Comment by nightpool** [comment]
yeah, we definitely want to message this and make sure that we proceed
slowly.

**Comment by SophiaNOTLoren** [comment]
Questions:
1. Is peepr the same thing as the sidebar? If so, I'm one of those people who absolutely loathes it (and keeps wishing there were more ways to use new-xkit to get rid of it completely.)

2. How would i go about testing this PR before any commit? it's been a while since I worked with all of this, and I'm kinda rusty... sorry.

**Comment by nightpool** [comment]
@SophiaNOTLoren Yes, the sidebar

**Comment by SophiaNOTLoren** [comment]
Okay... and how about for the second question -- testing this before it's merged?

**Comment by wooziwoozi** [comment]
I am someone who is for Peepr... I don't really understand why people loath it so much when it is basically the same extension as View on Deck.. only it... works. I find it hard to believe this issue effects them because how can they even use View on Dash in its current state?

I mean:
View on Dash: http://i.imgur.com/rx66c2v.png
Peepr: http://i.imgur.com/H3O5AJg.png

Anyway, I would, at the very least, appreciate having the option to chose to use Peepr with things that use View on Dash instead. (Such as the Blog Tracker)

**Comment by nightpool** [comment]
Blog tracker now uses Peepr by default, as of this afternoon.

are there other places using view on dash that we should change?

**Comment by SophiaNOTLoren** [comment]
Honestly my biggest (only?) gripe with Peepr is that it's a huge waste of screen real-estate; VoD plus Panorama on a widescreen display uses ~80% of my browser window, where Peepr uses maybe ~25% at best, with teensy-tiny versions of post's images. But if it's a choice between barely-can-see-but-functioning, and actually-visible-but-broken, I'll take the former.

And to answer @nightpool 's question, I don't know about "places using view on dash," but being able to simply choose a blog to view would be pretty useful, since that's the only thing that I used the VoD extension for previously.

**Comment by wooziwoozi** [comment]
_"with teensy-tiny versions of post's images."_ -- Huh? I guess I don't understand because Peepr looks the same to me as my dash. I don't use panorama or whatever that is though. 

I don't know what browser you use, but I use an extension called Imgus which may be useful to you. It allows you to hover image links and see the image without clicking on anything. This may come in handy for you because it lets you hover images with HD links why I feel may be what you mean...?

**Pull request closed without merging**
