### PR TITLE
Cause ER to halt execution if post is a link

### LINKED ISSUE #747: Editable Reblogs borks on links
Per a discussion with a user in Gitter...it appears that ER is eating new content added to links when reblogging.

The JSON being sent for the link when ER is disabled is:

```
"post[tags]": "",
"post[two]": "http://thinkprogress.org/economy/2015/11/09/3720495/wisconsin-begin-drug-tests/",
"post[three]": "<p> Of course the management of companies that recieve public funding and/or subsidies should be tested for drugs and of course Wall Street Trader (any licensed stock market trader) should do monthly drug tests.</p>"
```

With `post[two]` being the original link URL and `post[three]` being ONLY the added content.

Since this means that Tumblr's backend will not recognize any changes to the reblog tree above the added content anyway, I believe this means links should be added to the "Abort" list for ER (i.e., like with chats and quotes, the extension should halt and not run on any post-window determined to be of that post type). 

I'll work on getting this turned around unless anyone has any objection.

### PR DESCRIPTION
**Pull request by blackjackkent**
Resolves #747

### CODE REVIEW

**Comment by bvtsang** [comment]
LGTM

@homu r+

**Comment by nightpool** [comment]
this isn't permanent behavior, correct? there's no reason we shouldn't be
able to edit reblogs on link posts

**Comment by bvtsang** [comment]
It's possible that maybe we got something wrong in our svc request, but until then editing previous content in the reblog tree takes no effect.

**Comment by blackjackkent** [comment]
@nightpool please see the associated issue #747 for the reasoning behind this. (LMK if it doesn't make sense.)

**Pull request merged**
