### PR TITLE
Remove Satsukimous

### PR DESCRIPTION
**Pull request by Wolvan**
Extension to abusable

### CODE REVIEW

**Comment by nightpool** [comment]
screenshots are inherently abusable. I don't see anything specific to satsukimous that's worse then that? Maybe if we make satsukimous fake names visually distinct from normal blog names? i.e. not bold or something

**Comment by Wolvan** [comment]
>yes. But not everyone knows how to do that
installing an extension and changing 3 settings is making it too easy

Additionally are we responsible for not giving tools that are capable of being abused, same reason as why mutual follower and unfollower checkers are banned

**Comment by ThePsionic** [comment]
I have been thinking about this, and I don't think removing Satsukimous altogether is necessary. The only thing that does need to go is the renaming of "Anonymous" to anything else, in my opinion. This way people can't abuse Satsukimous while others are still able to use it as a joke element.

**Comment by nightpool** [comment]
Would making the renamed blog visually distinct be an acceptable compromise?

**Comment by ThePsionic** [comment]
@nightpool What kind of distinctiveness are you thinking about?

**Comment by Zarggg** [comment]
I haven't really paid much attention to this extension, but wasn't its original purpose to just replace Tumblr's avatar graphic for anonymous asks with Satsuki? I don't think there would be much to "abuse" if it did nothing beyond that.

**Comment by bvtsang** [comment]
Context for the potential for abuse of Satsukimous: http://new-xkit-discussion.tumblr.com/post/130570278949/on-the-future-of-satsukimous

**Comment by dlmarquis** [comment]
@blackjackkent and I discussed a few ideas for names:

1) Force the first letter to be capital. Pros: subtle, but fucks over anyone trying to insert a url. Cons: possibly too subtle for the average bear.

2) Highlighting/colors. Pros: very obvious. Cons: ugly, we'd have to be careful not to screw up the greyed urls tweak, themes, or visually-impaired users.

3) Small caps. Pros: definitely not a url. Cons: still potentially ugly, might not render correctly.

**Comment by 0xazure** [comment]
Closing this as it's been generally agreed that Satsukimous will not be removed, but other changes will be made to reduce/avoid concerns of impersonation, etc.

Those other changes should be in another PR.

**Pull request closed without merging**
