### PR TITLE
Issue 1073: Pressing Alt button will no longer break help icon.

### PR DESCRIPTION
**Pull request by lorrocha**
Addressing https://github.com/new-xkit/XKit/issues/1073

### CODE REVIEW

**Comment by nightpool** [comment]
Wait, that was it? nice.

You'll need to bump the version of the file, or else XKit won't update the extension. We follow http://semver.org/

(although we realized after making that decision that semver doesn't really make sense for non-user-facing stuff but w/e, it should mostly be straight-forward and intuitive)

**Comment by Wolvan** [comment]
image
kind of squashes the buttons together. You also forgot to bump the version, otherwise this looks good so far

**Comment by nightpool** [comment]
(Additionally, cool tip! if you include "closes #1073" in your commit message, it'll close the issue automatically when we merge it)

**Comment by blackjackkent** [comment]
Above issues resolved; tested, lgtm.

@homu r+

**Pull request merged**
