### PR TITLE
Add Vanilla Video extension

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by nightpool** [comment]
do vines/youtube embeds that are in video posts still follow/loop/autoplay?

**Comment by hobinjk** [comment]
Yes, Vines and Youtube are unaffected. I actually found a neat trick for getting Vines to not autoplay and can easily adapt the tumblr_video approach to YouTube. I'll update the PR later this evening, or during my lunch break because I am now excited about how this could actually work and single-handedly fix everything about Tumblr's video playing.

**Comment by nightpool** [comment]
FWIW I actually like that videos scroll with me, but that may just be me :D

**Comment by bvtsang** [comment]
@nightpool Don't worry, I prefer that too :P

**Comment by Wolvan** [comment]
this does look good to me, works as expected. You still busy with this, @hobinjk?

**Comment by hobinjk** [comment]
I am in favor of merging this as a beta revision, especially since the improvements I wanted to make require core-extension-level updates.
@homu r=Wolvan

**Pull request merged**
