### PR TITLE
Blacklist preserve href with comments

### PR DESCRIPTION
**Pull request by hobinjk**
Based on @PalanteJon's great work in #745, this just adds my review comments. It should be re-reviewed by someone else for sanity's sake. Many users have requested this feature because the only constant with spam posts is that they use Google's link shortener.

### CODE REVIEW

**Comment by nightpool** [comment]
uhh this regex is really flakey `<a href='tumblr.com'></a>` and `<a href=tumblr.com></a>` are also valid html.

**Comment by hobinjk** [comment]
@nightpool As far as I can tell Tumblr only generates `href="link"` even when I write `href=link` in the HTML editor

**Comment by nightpool** [comment]
yeah I'm not too worried. 

@homu r+ rollup

**Comment by nightpool** [comment]
@homu rollup-

**Pull request merged**
