### PR TITLE
Bump Safari version; Add update manifest file

### LINKED ISSUE #681: Host Safari Extension's update.plist
Good news: We actually got reviewed by the Apple store!
Bad news: "During our review, we found that you have not enabled automatic updating for your extension."

This requires an `update.plist` file as described in https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/UpdatingExtensions/UpdatingExtensions.html

The current location I want to put this is http://new-xkit.github.io/XKit/Safari/update.plist. See #643 for the issue surrounding an equivalent Firefox file.

### PR DESCRIPTION
**Pull request by hobinjk**
Fixes #681

### CODE REVIEW

**Comment by Wolvan** [comment]
We have to manually merge that PR into gh-pages I guess?

**Comment by hobinjk** [comment]
I think the gh-pages branch will auto-update as a side-effect of the auto-building

**Comment by Wolvan** [comment]
Right, let's try if it works
@homu r+

**Comment by hobinjk** [comment]
I was wrong, the gh-pages branch will not auto-update. Time to merge and pray

**Comment by hobinjk** [comment]
Or r+ an unrelated change

**Pull request merged**
