### PR TITLE
The Great Icon Redesign

### PR DESCRIPTION
**Pull request by shutterspeak**
First part of a multi-part effort to update XKit's iconography.

Preview: 

image

### CODE REVIEW

**Comment by Wolvan** [comment]
Looks very good, well done!

**Comment by shutterspeak** [comment]
non-icon icon chart

**Comment by Wolvan** [comment]
Looks good. @homu r+

**Comment by nightpool** [comment]
@shutterspeak in the future, can you have the icons chance labelled in the pull-request? it's kind of hard for me to tell which icon is supposed to go with which extension (I can guess some of them, but not all of them)

**Comment by shutterspeak** [comment]
@nightpool sure thing!

**Pull request merged**
