### PR TITLE
One-Click Postage: Set default blog whenever popup menu is opened

### LINKED ISSUE #44: Quick Reblog defaults to wrong blog
One Click Reblog defaults to incorrect blog. May be fixed.

### PR DESCRIPTION
**Pull request by bvtsang**
Plus some refactoring.

Fixes #44.

### CODE REVIEW

**Comment by bvtsang** [comment]
Wait, I may have forgotten about the case where `preferences.default_blog.value === ""`.

**Comment by WyohKnott** [comment]
You need a check for ```this.preferences.show_blog_selector.value === true```, otherwise ```$("#x1cpostage_blog)``` does not exist because the blog selector is not constructed in the first place.

**Comment by hobinjk** [comment]
This isn't working for me locally, the last selected blog is still the one that is selected instead of the default.

**Comment by hobinjk** [comment]
This started working for me locally, good work!
@homu r+

**Pull request merged**
