### PR TITLE
Remove fallback to old XKit servers

### LINKED ISSUE #632: Depreciate fallback URLs
Ideally this should have gone out with `v7.7.1`, but now that the SSL/TLS certificates on the old XKit servers are dead, we should really remove the [fallback behaviour](https://github.com/new-xkit/XKit/blob/cfc7137ab37d569ccacb59645dcc52d9a03e5df1/xkit.js#L240) since instead of outright failing the download, mixed-content requests seem to cause XKit to hang in most browsers.

### PR DESCRIPTION
**Pull request by 0xazure**
Remove fallback to old XKit servers.

Remove unused `XKit.servers` functions.

Point `festivus_lights` at a valid URL that serves the correct asset.

Fixes #632.

Unfortunately due to how the fallbacks for `XKit.download.page()` were implemented, we can't update the  function calls in `themes.js`, `xcloud.js`, `xkit_updates.js`, and `xkit_preferences.js` to point to the new endpoints and get rid of the long `if` block in `XKit.download.page()` until we create a new browser release with these changes to core.

### CODE REVIEW

**Comment by nightpool** [comment]
can we not override download.page in patches? or do we just not want to?

**Comment by 0xazure** [comment]
We certainly could, and we may have to, but I treat that as a last resort because it means we have more clean-up to do later.

I mean, conceivably we could move (almost) _everything_ to `patches` and just be done with `xkit.js` in its current incarnation.  Might be something to look into, actually.

**Comment by nightpool** [comment]
@0xazure i'm pretty down with that tbh. (isn't that one of the goals of
modularization or nah?)

**Comment by 0xazure** [comment]
Some of the goals of modularization are to break things up into logical chunks and avoid thousand-line monolith files, as well as de-dupe overriding (which shouldn't be happening in the first place).  But I'm liking the idea of deprecating `xkit.js` and merging it into `xkit_patches` more and more, in the interim.

Closing this in favour of merging the files, which will be done in a PR targeting `master`.

**Pull request closed without merging**
