### PR TITLE
Remove video ads again in Anti-Capitalism

### PR DESCRIPTION
**Pull request by kdmnance**
Video ads are now under "video-ad" and "standalone-ad-container"

### CODE REVIEW

**Comment by kdmnance** [comment]
Same change created just before me by nightpool

**Comment by nightpool** [comment]
actually yours is better I forgot the version number

**Comment by nightpool** [comment]
@homu r+

**Comment by nightpool** [comment]
FYI @kdmnance in retrospect every "video-ad" is inside of a "standalone-ad-container" so we didn't need both selectors

**Comment by kdmnance** [comment]
I realized just after I put in my pull request, sorry about that

**Comment by nightpool** [comment]
no problem, just making sure you knew

**Pull request merged**
