### PR TITLE
Mirror Paperboy and framework_version files

### LINKED ISSUE #168: Paperboy and framework_version.php are not mirrored
All other files that normally come from XKit's servers have equivalent mirrors on our Github pages. These two don't and it has caused issues for at least one person when old XKit went down for a bit.

### PR DESCRIPTION
**Pull request by hobinjk**
Fix #168.

### CODE REVIEW

**Comment by nightpool** [comment]
this doesn't appear to have the actual files?

**Comment by hobinjk** [comment]
The actual files will be pushed to the gh-pages branch. They're not on master due to how the dist/ directory is laid out.

framework_version.json will be:
```
{"server":"up","frameworks":[{"name":"firefox","version":"7.7.1"},{"name":"chrome","version":"7.7.1"}]}
```

paperboy.json will be:
```
{"server":"up","news":[]}
```

The reason for the 7.7.1 in framework_version is that this change can only land in the hypothetical 7.7.1 release because it modifies xkit.js.

**Comment by nightpool** [comment]
@hobinjk feels like we should have a place for this stuff to live in the
main branch, but I'm down for whatever.

**Comment by hobinjk** [comment]
@nightpool  I agree, that would be worth filing a follow-up issue.

**Comment by bvtsang** [comment]
LGTM

@homu +r

**Comment by bvtsang** [comment]
@homu r+

**Pull request merged**
