### PR TITLE
update Hide Avatars for new dashboard

### PR DESCRIPTION
**Pull request by AprilSylph**
Screenshot at 2020-05-07 15-40-38

### CODE REVIEW

**Comment by AprilSylph** [comment]
image

**Comment by hobinjk** [comment]
Oh, sorry! I meant the avatar at the top of a post although hiding the in-blog avatar is also a good addition to have.

In a wide window:
Screen Shot 2020-05-13 at 6 31 13 PM

In a thin window:
Screen Shot 2020-05-13 at 6 31 20 PM

**Comment by AprilSylph** [comment]
ohhh i forgot that happened! i'll see what i can do about it

**Comment by AprilSylph** [comment]
image

**Comment by hobinjk** [comment]
Great! Nice to have all the angles covered

**Pull request merged**
