### PR TITLE
modern One-Click Postage button icons

### PR DESCRIPTION
**Pull request by AprilSylph**
purely aesthetic update

goodbye images, hello `tumblr-icons` font

| Old | New |
| :---: | :----: |
| screenshot 2018-06-30 at 19 38 42 | screenshot 2018-06-30 at 19 38 15 |

### CODE REVIEW

**Comment by hobinjk** [comment]
This is likely just a firefox/mac thing but on my local setup the icons are slightly misaligned:
screen shot 2018-07-09 at 5 54 06 pm

**Comment by AprilSylph** [comment]
oh huh, i tested it on FF but completely forgot about the reverse UI (unless I'm using it, in which case I forgot about the standard UI), damn

**Comment by AprilSylph** [comment]
amended for chunky interface
image

**Comment by hobinjk** [comment]
LGTM, the facebook icon is a few pixels off but #deletefacebook
screen shot 2018-07-14 at 12 33 12 pm

**Comment by AprilSylph** [comment]
yeah, I couldn't find a solution for making the facebook logo align properly on all browsers so decided not to try lmao

**Pull request merged**
