### PR TITLE
Add check for when Old Xkit is installed

### PR DESCRIPTION
**Pull request by dlmarquis**

### CODE REVIEW

**Comment by dlmarquis** [comment]
Also added commenting of the dashboardGL code because I am super competent and that was totally on purpose

**Comment by nightpool** [comment]
maybe do a rebase instead so we don't get any merge commits?

**Comment by dlmarquis** [comment]
Sorry about that. I'm new to commandline git and I was having some problems.

**Comment by dlmarquis** [comment]
I force-pushed the history change.

**Comment by dlmarquis** [comment]
Annnd I have no idea what's up with that error since I haven't actually edited any of the files.

**Comment by hobinjk** [comment]
It was an intermittent because Travis CI has Curmudgeonly Infrastructure

**Comment by hobinjk** [comment]
Tested locally and it does not break anything, despite some loser editing my comments.
@homu r+

**Pull request merged**
