### PR TITLE
[edible_reblogs] Properly name and destroy the post listener.

### PR DESCRIPTION
**Pull request by nepeat**
The bread shouldn't come back after unchecking the 'hell box' in the settings.

### CODE REVIEW

**Comment by nightpool** [comment]
nah the bread coming back after unchecking the box is a feature.

**Comment by nightpool** [comment]
closing as feature.

**Comment by ThePsionic** [comment]
Don't be like that, @nightpool.

**Comment by ThePsionic** [comment]
LGTM @homu r+

**Comment by ThePsionic** [comment]
@nepeat informed me that this was a troll and that I am dum
@homu r-

**Pull request merged**
