### PR TITLE
NotificationBlock: fix typo + refactoring

### PR DESCRIPTION
**Pull request by bvtsang**

### CODE REVIEW

**Comment by Wolvan** [comment]
Looks alright to me, can I give a r+?

**Comment by bvtsang** [comment]
Go for it!

**Comment by Wolvan** [comment]
r+

**Comment by Wolvan** [comment]
@Homu r+

**Comment by bvtsang** [comment]
What happens if you try lowercase homu?

**Comment by Wolvan** [comment]
call me dumb, @bvtsang, but I don't have a clue on how to do it

**Comment by Wolvan** [comment]
@homu r+

**Comment by bvtsang** [comment]
Let me try to get someone to add you to the list of approved reviewers.

**Comment by hobinjk** [comment]
@homu r=Wolvan

**Comment by Wolvan** [comment]
@hobinjk for future reference, did you add me to the reviewers now?

**Comment by hobinjk** [comment]
@Wolvan Yes, sorry for rushing off. You can view the current list of reviewers [here](http://homu.io/r/new-xkit/XKit). I have no idea who has the rights to add people.

**Pull request merged**
