### PR TITLE
Bring PostArchive to 1.0.0

### LINKED ISSUE #448: Post Archiver doesn't autofill title field from reblogged posts on dash
Tested with text, photo, chat, video, and link posts. Only reblogged chats auto-fill the field because tumblr didn't muck with them.

Original posts still seem to work fine in my limited testing.

### LINKED ISSUE #600: Text Input capped to 512KB by default
That means you are only able to use 524288 characters in any text input from XKit. This becomes a problem especially when you have a lot of posts in post archiver that you want to ex- and afterwards import again, since that can easily exceed the 512KB limit, breaking the import JSON anhd making it impossible to restore the post archive

### PR DESCRIPTION
**Pull request by finagle29**
With these PR, PostArchive should be stable enough to warrant a major version release.

Should fix #448.
Unless there are other inputs where users could be pasting in more than 512KiB of text, this also fixes #600.

### CODE REVIEW

**Comment by coderpatsy** [comment]
Can we get a (readonly) textarea for the export too with a [.select()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select) call? The range code seems to be broken on my Firefox at least. Plus a textarea would allow one to press ctrl-a and get all the text in itself instead of the whole page, in case the javascript fails.

**Comment by finagle29** [comment]
Updated so that the export uses a readonly textarea and is selected with a `.select()` call.  Titles should be correctly populated from reblogs.  Embedded video width is now 540px to match Tumblr-hosted video and the new picture layout.  Blog icon (in the archived from {blog} section) was increased to improve readability and bring it more into line with what Tumblr uses on the dash.

**Comment by dlmarquis** [comment]
This is a complete nitpick, but can you give more detail on what the initial commit changed? There should be something more than the version change mentioned, in case we have to dig through these commits in the far future or something.

**Comment by hobinjk** [comment]
It would be good to provide documentation on how a user can take their copied JSON from old XKit and save it to a file for New XKit to handle (or provide an optionally-shown textarea for importing from old xkit). Otherwise this LGTM

**Comment by finagle29** [comment]
PostArchive before this version doesn't correctly sanitize (not sure if this is the right word) JSON for export (picture shows what i'm trying to say).  Importing from old XKit would require manually updating PostArchive.  Should I create a page on -extension detailing the manual upgrade process and link to that in the import dialog in PostArchive?
image

**Comment by hobinjk** [comment]
That sounds like a good solution.

**Comment by hobinjk** [comment]
Tested locally and WFM. Great work!
@homu r+

**Pull request merged**
