### PR TITLE
Remove account popover clicking approach

### PR DESCRIPTION
**Pull request by hobinjk**
Instead of trying to show then hide the account popover to get a list of
blogs just fall back to the cached list.

### CODE REVIEW

**Comment by hobinjk** [comment]
In other news, fixing issues is really easy when they're happening on your computer

**Comment by nightpool** [comment]
aint that the truth

I'm worried that the problem is tumblr changing their blog code, so i'm a little wary to approve this. does the first method fail consistently? it was for some users.

**Comment by hobinjk** [comment]
The only reason the first method fails for me is if the message sent from the injected code doesn't arrive before `get_blogs` is called. I can leave in the non-clicky parts of approach 2, but the main problem I was having with this bug is that it would trigger the Old Sidebar behavior where you can't left click on anything

**Comment by nightpool** [comment]
Aaaaaa that was my *second* though.

Yeah then this should be fine, but we should also make sure we're caching
the blogs as they come in, in case we don't happen to call get_blogs again
anywhere

**Comment by hobinjk** [comment]
Updooted with caching and the fallback semi-intact

**Pull request merged**
