### PR TITLE
New Extension - Made the new Reblog layout a little bit more bearable

### PR DESCRIPTION
**Pull request by macleodsawyer**
Helps add margin to the new layout, comes with four options
- Move to underneath username
- Add border to the side
- Remove username and align the text to the side of the avatar (looks really clean)
- Remove avatar and just have usernames. 

All of these options work with each other activated.

I originally made this for myself, but over 120+ people asked for it on my blog when I posted the screenshots.

Tested with most of the other extensions, does not affect them.

Screenshots:

### CODE REVIEW

**Comment by Wolvan** [comment]
@nightpool is working on #419 maybe talk to him about it?

**Comment by macleodsawyer** [comment]
@Wolvan left a note on the thread, it should be its own extension not an addition to Tweaks.

Fixed the lint error, thanks for reminding me!

**Comment by macleodsawyer** [comment]
Added two new options, 

- Remove username and align the text to the side of the avatar (looks really clean)
- Remove avatar and just have usernames.

**Comment by nightpool** [comment]
Every other dashboard style change is in tweaks. This is out of scope as a new extension. 

Happy to integrate some of these into the tweaks changes when I get home though.

**Comment by Wolvan** [comment]
@nightpool You said yourself that we should put all that in a new extension when we were talking about having it in ER. Also, with this much functionality by itself, I definitely wouldn't mind it being a seperate extension

**Comment by macleodsawyer** [comment]
@nightpool I wouldn't say it's out of scope. These changes reflect more than just dashboard, they reflect the popouts, search pages, blog pages, and more. 

Tweaks has an incredible amount of options already, there is no reason to add another four to it.

**Comment by ThePsionic** [comment]
Personal opinion, I would favor #426 over this one. A separate extension is recommended imo, because if we do it in Tweaks we get the same problem we already have ("Where is this thing? I can't find it" "Look in the ten thousand options in Tweaks")

**Comment by Wolvan** [comment]
@ThePsionic I would actually merge the functionality of #421 and #426 into one extension (because some people do actually like the overall looks of the new design), but @nightpool and @0xazure (I think it was) want to have consistency with the extensions and say this doesn't need it's own extension OR we would have to debloat Tweaks BEFORE having these seperate extensions

**Comment by ThePsionic** [comment]
@Wolvan in that case debloating Tweaks is definitely a thing we have to do. It's quite bad atm. Several things can be put in other extensions ("trending" badges at the bottom of posts could easily be brought under No Recommended).

**Comment by Wolvan** [comment]
@ThePsionic I agree with you, but that belongs into it's own issue. See #427

**Comment by nightpool** [comment]
hey ya'll (@wolvan @ThePsionic @macleodsawyer) I'm going to write code that changes the entire display of reblogs, and then this will be a feature of that 

that sound like a good compromise to everyone?

**Comment by Wolvan** [comment]
@nightpool that sounds fair to me

**Comment by macleodsawyer** [comment]
@nightpool sounds good.

**Comment by nightpool** [comment]
bong bong

**Pull request closed without merging**
