### PR TITLE
ext/show-picture-size: Fix element position in dom

### PR DESCRIPTION
**Pull request by TiMESPLiNTER**
Fixes pic size element position in dom for media-posts without link. Now all picture size elements should get displayed in the according picture again.

### CODE REVIEW

**Comment by hobinjk** [comment]
There's some kind of "flipcard" css class that Tumblr uses for photos with EXIF data that hides the picture size div by raising the photo to z-index 9. I can file this as an issue to look at in the future or you can handle the edge case now, whichever you prefer.

Otherwise, this looks good to me once you bump the version number. Thanks for the great work!

**Comment by TiMESPLiNTER** [comment]
@hobinjk thx for your feedback. I bumped the version number and raised the z-index für the picture size div to 10 as a quick fix.

**Comment by TiMESPLiNTER** [comment]
@hobinjk Okay I pushed another commit in which I switch from `.parents()` to `.closest()` to append the div with the pic size. I also added a line in the `destroy` property to remove the added divs again when the extension gets disabled.

**Comment by hobinjk** [comment]
Great work! LGTM
@homu r+

**Pull request merged**
