### PR TITLE
remove joke extensions

### PR DESCRIPTION
**Pull request by AprilSylph**
removes extensions:

- April Fool's
- Bubblr
- Edible Reblogs
- Elevator
- Fresh Prince
- Sharplr

but does NOT add them to the spring cleaning list, since they are not harmful or truly obsolete (having had no actual use-cases in the first place). this PR has several purposes:

1. reduce clutter in the `Extensions/` folder
2. reduce the total number of extensions we need to port to the React site
3. reduce user confusion (particularly in the case of Edible Reblogs)
4. make the Get Extensions tab easier to navigate

(reviews requested based on the authors of these extensions; please do not merge until both are fulfilled)

### CODE REVIEW

**Comment by invalidCards** [comment]
Can we make Elevator an option for Scroll To Top?

**Comment by AprilSylph** [comment]
there is no Scroll To Top extension, the scroll to top button is a vanilla feature

**Comment by AprilSylph** [comment]
it's maybe negligible harm, but the gallery being padded with extensions that users may install for fun or curiosity and then either immediately or very shortly uninstall, or never use past the first 5 minutes of install, doesn't sit right with me.

- if the user immediately uninstalls or disables a joke extension, that action resets their position in the Get Extensions tab, which hurts the experience of browsing the gallery, which is very important for new users.
- if the user disables it soon after or never uses it, that unnecessarily pads out their list of installed extensions, making navigation of the My XKit tab marginally more difficult, and keeps unnecessary code on their machine.
- if the user uninstalls it soon after, that's proof they never needed it.

i don't think we should continue to host, or (given the nature of the gallery) advertise, userscripts that nobody needs.

**Comment by AprilSylph** [comment]
splitting this PR into per-extension removal PRs so that individual cases for these extensions can be made

**Pull request closed without merging**
