### PR TITLE
J to next page

### LINKED ISSUE #451: Pressing J doesn't always navigate to next page
Steps to reproduce:

1. Install J/K Across Pages
2. Settings > Dashboard > Disable endless scrolling
3. Visit your dashboard
4. Keep pressing J until you reach the bottom of the scren
5. Press J
6. Expect to navigate to next page
7. Observe that nothing happens

This doesn't happen all the time, but I can reproduce it fairly reliably.

### PR DESCRIPTION
**Pull request by bvtsang**
Fixes #451

### CODE REVIEW

**Comment by bvtsang** [comment]
TODO:

- [ ] Test with Header Options

**Comment by nakengelhardt** [comment]
It's a very minor thing, but this requires an extra click in cases where the last post is already entirely on the screen, but the window isn't scrolled completely to the end yet. Since there's nothing interesting in the footer, would there be a way to skip that?

**Comment by Wolvan** [comment]
LGTM, want me to call homu or do you want to add @nakengelhardt's suggestion first, @bvtsang?

**Comment by bvtsang** [comment]
Good thing you brought that up. Let's think this through.

If the last post is already entirely on the screen and the window hasn't scrolled completely to the end yet, then there are now two possible cases:

1. User presses J and navigates to the next page
  - Pros:
    - Consistent with current behavior
  - Cons:
    - Code relies on arbitrary numbers (`scrollBufferJ` and `scrollBufferK`) that may change in the future (like if Tumblr's layout changes)
2. User presses J and scrolls to the bottom of the screen
  - Pros:
    - Establishes new consistency: navigate to next page only when at bottom of screen
  - Cons:
    - User needs to press J one more time

I prefer the second case because it favors long-term maintainability. The condition for navigating to the next page (whether the last post was close enough to the bottom) is changed for a more stable one (detecting whether the user is at the bottom of the screen). And I don't think pressing J one more time is too significant a con.

**Comment by dlmarquis** [comment]
I think I'd prefer to see the first option, honestly. It would be more streamlined from a user perspective, and it doesn't seem like staff messes with j/k navigation too often anyway.

**Comment by bvtsang** [comment]
Alright, I've restored it back to case 1 using @nakengelhardt's changes from #451.

**Comment by dlmarquis** [comment]
LGTM

@Homu r+

**Comment by dlmarquis** [comment]
Goddamn autocaps

@homu r+

**Pull request merged**
