### PR TITLE
Add bigger small text tweak

### PR DESCRIPTION
**Pull request by Wolvan**
Request from support chat

### CODE REVIEW

**Comment by dlmarquis** [comment]
LGTM
@homu r+

**Comment by dlmarquis** [comment]
...is Homu failing because of something with the Linux Kernel?

**Comment by ThePsionic** [comment]
@homy retry

**Comment by ThePsionic** [comment]
@homu retry

**Comment by ThePsionic** [comment]
@dlmarquis ftfy

**Pull request merged**
