### PR TITLE
Fast follow on get_blogs changes

### LINKED ISSUE #945: Throwing errors on all blogs in Chrome when logged in
Steps to reproduce:

1. Go to http://new-xkit-extension.tumblr.com/ (or any blog) with the developer console open
2. Observe this error: `Uncaught TypeError: Cannot read property 'allTumblelogs' of undefined`

Looks like it was introduced here:

https://github.com/new-xkit/XKit/pull/943/files#diff-f3c602f5caa159014c2f7557700de10cR130

### PR DESCRIPTION
**Pull request by nightpool**
A few fixes from today's changes

 - Silence extraneous errors 
 - Added external docs for escape_html. (are we supposed to be maintaining both of these?)
 - fix small correctness problem with blogs_from_tumblr
(Sorry, I was doign a lot of jQuery code checking at the time, and got the two patterns mixed up. Mia culpa)

fixes #945

### CODE REVIEW

**Comment by hobinjk** [comment]
Version bump, otherwise LGTM

**Comment by hobinjk** [comment]
@homu r+

**Comment by nightpool** [comment]
was adding the version bump as you said that :D

**Comment by nightpool** [comment]
or well, before I saw it at least lol

**Pull request merged**
