### PR TITLE
New extension: April Fool's

### PR DESCRIPTION
**Pull request by AprilSylph**
Adds an extension to bring back the best of this year's April Fool's stuff
- Framed avatars become a Mutual Checker thing
- AOL Instant Messaging becomes a Messaging Tweaks modification
- The Missing E becomes a Header Options... option?

AIM isn't perfect thanks to a little quirk of Messaging Tweaks that I don't have the energy to fix today, thus it's marked as experimental.

---
To-Do:
- [x] Automatically disable preferences when their requirements aren't met
- [x] Add remaining CSS for AIM that `.flag--aim-messenger` doesn't do
- [x] Add AIM sending sound
- [x] Add AIM receiving sound when the conversation isn't already open
- [x] Fully test each feature after the fun is over on vanilla Tumblr
(It's possible that Tumblr will remove the CSS this extension relies on, but they never delete their CSS files so if that happens the styles can just be ripped out from [here](https://assets.tumblr.com/client/prod/app/global.build.css?_v=afa3cca5923f46700fc2864f41a95402))
---
Merge prerequisites:
---
- [x] Merge #1526 
- [x] Merge #1518

### CODE REVIEW

**Comment by AprilSylph** [comment]
almost forgot to give it an icon! using a cropped "missing e", but am open to changing it to a framed Nx blog icon (or anything better anyone can think of) if we think that's distasteful

**Comment by AprilSylph** [comment]
damn, looks like tumblr finally removed the CSS for framed avatars and the missing e logo, will have to get the styles back manually. AIM is unaffected this time but who knows when they'll decide to remove that too? 😨

**Comment by AprilSylph** [comment]
alright, I added the CSS back directly (yay for tumblr not cleaning up their files!)
however there's a danger that tumblr will figure out how to properly delete the images on their servers in the future, so here's those: [avatar frame](https://user-images.githubusercontent.com/28949509/38433704-c8c4458c-39c3-11e8-8c75-04ab45c5608a.png), [missing e logo](https://user-images.githubusercontent.com/28949509/38433708-cdbe6d60-39c3-11e8-811a-0c2d7dfa67eb.png)

and the remaining CSS for AIM that we don't add is [here](https://gist.github.com/AprilSylph/c8203a5900ecca63a63ae7f3a07c5000) in case they decide to remove that, too!

**Comment by hobinjk** [comment]
Looks like the frame image is gone but the other functionality LGTM. It's probably good to put all the images into `Extensions/dist/page/images` since they're mysteriously disappearing

**Comment by AprilSylph** [comment]
@hobinjk were you using the updated Mutual Checker while testing? frames won't work otherwise. I'll still get on future-proofing it though

**Comment by AprilSylph** [comment]
oh nevermind, looks like it did get removed. my cache is playing tricks on me

**Pull request merged**
