### PR TITLE
Restoring xpreview note count popup to notifications plus

### LINKED ISSUE #1369: Notification+ doesn't work on new activity page
Several notification+ features need to be updated to the new activity page. Of particular note is XPreview, which is useful because tumblr seems to have removed their built-in feature for this (showing the amount of notes a post has when you're hovering over an activity)

### PR DESCRIPTION
**Pull request by blackjackkent**
Addresses xpreview issue mentioned in #1369.

---
resolves #1369 
closes #1379

### CODE REVIEW

**Comment by AprilSylph** [comment]
Clone of #1379 ?

**Comment by blackjackkent** [comment]
Oop. That would explain why @nightpool said it was fixed in #1369. My bad.

FWIW this PR does fix the show_bigger_preview option as well, which is not addressed in that other PR.

**Comment by hobinjk** [comment]
Can you clean up the commit history on this? Rebasing https://github.com/new-xkit/XKit/pull/1412/commits/3de6e0c507b136b5939ce55bbbbdb529cb320b4e on master should work.

**Comment by AprilSylph** [comment]
given that 
1. this is the much less broken Notifications+ PR
2. you originally did the exact same thing as #1379 and more without actually looking at it

I think this is the one to work on - I would merge #1379 as is but trying to use the bigger preview is a lot uglier there. I think it would be perfectly fair to remake your commit as it was, before we get onto the next problem:

the bigger preview option doesn't seem to work anymore, and is arguably even useless now that
- the default activity feed gives bigger previews now
- peepr is a thing
- as far as I can remember I haven't heard a single user complain about the lack of this feature

so, I would say either fix the bigger previews up, or remove the option entirely if that takes more than an hour

**Pull request closed without merging**
