### PR TITLE
Package code with extension

### PR DESCRIPTION
**Pull request by marcustyphoon**
This creates a v7.10 version which does not execute remotely hosted code, instead including all resources within the web extension package.

Extension code is still stored in, and executed out of, local storage, which preserves the XKit Editor functionality. This therefore doesn't fulfill an MV3 requirement, but it's better than it was. (I also have the majority of a working MV3-compliant, no-editor branch, but it has a few problems at the moment.)

This setup requires some careful thought about upgrade paths: any extension code committed with and following this change can assume it's running in at least the XKit version it's shipped with, but we **cannot** assume the user has the latest version of any extension, including internals. A user upgrading from v7.9 will be running the changes to `xkit.js` and to the extension's packaged files, but will not have updated extensions until (the old version of) `xkit_updates` eventually fires and saves them to local storage. We get lucky here: the spot to patch is inside `xkit.js`, so implementing this correctly is not impossible as long as we stick to the same API surface that `xkit_updates` expects.

---

Edit: Oh, right, the downgrade story.

> any extension code committed with and following this change can assume it's running in at least the XKit version it's shipped with

Note that this is NOT true if a user installs a previous version of XKit over a version that comes after it: the script code is stored in local storage, as mentioned, so whatever new script versions the user has will stay around in this case. We should, of course, not publish future script versions to github pages in the old format to avoid breaking unupdated v7.9.3 installations which this PR already ensures. (`npx gh-pages --add` means "don't remove old files," so as long as we leave the json files intact in the `gh-pages` branch, they'll be there forever.)

Besides a fix I just realized I need to make to the `run_order` variable in `xkit_patches` and will make immediately after submitting this edit, I don't think any of the changes I have made to script files in this PR will break if they are executed on v7.9.2. The MV3 branch I'm experimenting with absolutely will, though, unless I do some fallback stuff.

(I imagine the number of people downgrading 7.10 would be zero, and if one did it would be unsurprising if things broke, so this does not seem at all important. I **could** see someone downgrading a hypothetical MV3 version back to MV2, to get back xkit editor support, so it's more worth thinking about in that case.)

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Used to generate index files:

```js
// build_index.mjs
import fs from "node:fs/promises";
import path from "node:path";

(async () => {
	const extensionList = (await fs.readdir("Extensions"))
		.filter(fileName => fileName.endsWith(".js") && !fileName.endsWith(".icon.js"))
		.map(fileName => path.parse(fileName).name);
	await fs.writeFile("Extensions/_index.json", JSON.stringify(extensionList, null, 2), {
		encoding: "utf8",
		flag: "w+",
	});

	const themeList = await fs.readdir("Themes");
	await fs.writeFile("Themes/_index.json", JSON.stringify(themeList, null, 2), {
		encoding: "utf8",
		flag: "w+",
	});
})();
```

Used to verify that the js transforms here exactly match the output of the gulp build server:

```js
// test_build.mjs
import fs from "node:fs/promises";

const loadFile = path => fs.readFile(`.${path}`, "utf8");

async function build() {
	const galleryData = await getGalleryData();
	await fs.writeFile("Extensions/dist/page/gallery.json", JSON.stringify(galleryData), {
		encoding: "utf8",
		flag: "w+",
	});

	const listData = await getListData();
	await fs.writeFile("Extensions/dist/page/list.json", JSON.stringify(listData), {encoding: "utf8", flag: "w+"});

	const themeGalleryData = await getThemeGalleryData();
	await fs.writeFile("Extensions/dist/page/themes.json", JSON.stringify(themeGalleryData), {
		encoding: "utf8",
		flag: "w+",
	});

	const extensionList = JSON.parse(await loadFile("/Extensions/_index.json"));
	for (const id of extensionList) {
		await fs.writeFile(`Extensions/dist/${id}.json`, JSON.stringify(await getExtensionData(id)), {
			encoding: "utf8",
			flag: "w+",
		});
	}
}

build();

/* functions from the bottom of xkit.js */
```

**Comment by hobinjk** [comment]
Incredible work! Your efforts are an inspiration both here and over in optimizer-land

This PR passed my smoke test of build and install the current HEAD -> install this over it -> verify that stuff is still installed. I plan to take a look at the code and implementation tomorrow but really great stuff so far!

**Comment by marcustyphoon** [comment]
Note: this spams the developer console with `net::ERR_FILE_NOT_FOUND` errors since not every script has an icon and/or a CSS file. There's... probably a way around this?

**Review by hobinjk — APPROVED** [review]
I like the _index.json solution for the FILE_NOT_FOUND error spam problem. Overall the code looks good to me. One problem that may occur is if AMO's automated testing is based on whether `new Function`/`eval` is present at all but this is a great step even if it's onto that pressure plate

**Comment by marcustyphoon** [comment]
Yeah, if they disallow eval we would have to kill the editor and storing script bodies in storage, I assume. Which, I mean... maybe just doing that is smarter re: optimizing the ratio of effort spent on this thing to amount of functionality shipped to users, but I distinctly remember nightpool advocating for the continued existence of this project partially based on its editor functionality, which was one of the reasons I went out of my way to see if it could be (maybe, kinda) preserved. Perhaps I was misinterpreting that comment, though.

**Pull request merged**
