### PR TITLE
Fix Classic User Menu button + ask posts

### PR DESCRIPTION
**Pull request by coderpatsy**
The Classic User Menu button would appear in the bottom left of a post when mousing over the avatars in ask posts. Making the selector more specific fixes that.

### CODE REVIEW

**Comment by bvtsang** [comment]
Don't forget to add to remove that `mouseover` handler in the `destroy` function.

**Comment by coderpatsy** [comment]
Whoops, done.

**Comment by bvtsang** [comment]
Sorry, I should've been specific. What you've currently done is change the selector for the `XKit.extensions.show_more.store_data_avatar` handler; instead, what needs to be done is to add a new `$(document).off('mouseover', '.post_avatar .post_avatar_link', XKit.extensions.show_more.enable_classic_menu);` (because the old code didn't have this for whatever reason).

**Comment by coderpatsy** [comment]
Ah! Well that was easy enough (I hope).

**Comment by bvtsang** [comment]
LGTM

@homu r+

**Pull request merged**
