### PR TITLE
Fix for #807

### PR DESCRIPTION
**Pull request by namanix**
This fixes issue #807. Seems like you can only add tags when the tag box
is actually visible. DOM problem?

Also i removed a couple of unneeded comma's

### CODE REVIEW

**Comment by Wolvan** [comment]
It works for me, although you still have to bump the version. I also suggest that you set the display and opacity back to 0/none after you are done injecting the tags. (It's just a matter of ``$(".post-form--footer").css("display", "none"); $(".post-form--footer").css("opacity", "0");`` at the end of the inject function.

**Comment by namanix** [comment]
I will test if your solution also works. If so. Do i need to do another pull request or can i update this pull request somehow ?

**Comment by Wolvan** [comment]
Just update the branch you try to merge, Github automatically updates the PR
Maybe squash your changes if you know how to

**Comment by namanix** [comment]
I just tested it. But this is not an option. When i run $(".post-form--footer").css("display", "none"); $(".post-form--footer").css("opacity", "0"); after the tags are added the normal text posts don't show tags anymore. That's because tumblr doesn't add the tag bar with javascript on normal text and quote posts. So only a version number increase ? 0.6.7?

**Comment by Wolvan** [comment]
Alright, fair enough then. And yeah, version 0.6.7

**Comment by namanix** [comment]
Version number is changed to 0.6.7

**Comment by namanix** [comment]
How long does is usually take to get this update into the xkit that everybody can download from google chrome store ?

**Comment by Wolvan** [comment]
Fix works, LGTM
@homu r+

@namanix the update is actually available almost immediately after this has been merged into master. It's just a tiny delay of travis rebuilding the extension dist but then anyone can immediately update

**Pull request merged**
