### PR TITLE
Update Audio Downloader for the new style of audio posts

### LINKED ISSUE #1282: Audio Downloader doesn't work
I've updated the extension, and the download arrow does not appear for any audio post. I uninstalled xkit and reinstalled it and the audio downloader feature is still missing.

### PR DESCRIPTION
**Pull request by hobinjk**
Changes the class to look for on audio posts (`audio_player` becomes
`audio-player`). Removes logic that is already encompassed by get_posts.

Fixes #1282

### CODE REVIEW

**Comment by nightpool** [comment]
LGTM. there's a thing here about how audio downloader depends on the api unnecessarily, but I've had the code to remove it sitting on my computer for a month now and I haven't done anything with it, so I'm just going to approve this.

The harder dependency here is that it depends on a atesh server to add the correct download headers and name (which doesn't work half the time, depending on the browser). we'll probably want to rip that out at some point too.

@homu r+

**Comment by hobinjk** [comment]
@nightpool Is your code using the audio-source element? Its urls are making me feel guilty ([https://www.tumblr.com/audio_file/22839127381273testing/160135660088/tumblr_mzxpkv5xc31saddim?plead=please-dont-download-this-or-our-lawyers-wont-let-us-host-audio](https://www.tumblr.com/audio_file/22839127381273testing/160135660088/tumblr_mzxpkv5xc31saddim?plead=please-dont-download-this-or-our-lawyers-wont-let-us-host-audio) for example)

**Comment by nightpool** [comment]
yes, I felt guilty about that too until I realized they'd been there since like 2013 :P

**Comment by hobinjk** [comment]
🚢 ☠️ 😎 ☠️ 🚢

**Pull request merged**
