### PR TITLE
Allow saving of JSON Stringified Extension Object

### LINKED ISSUE #501: Saving JSON Object in the XKit Editor
That's been something that has been bugging me for some time when I tried importing custom extensions. Instead of just being able to copy the JSON string of the custom extension and pasting it in the editor, you have to manually go through adding stylesheet, script and icon since the JSON strings gets overwritten by the other tabs

### PR DESCRIPTION
**Pull request by Wolvan**
Fixes #501

### CODE REVIEW

**Comment by 0xazure** [comment]
In the current implementation, I see a problem in how it chooses which pane to save.  Correct me if I'm wrong, but if you're on the JSON pane, it will save the contents there, and if you're on any other pane it will re-generate the JSON and _then_ save.

This could lead to accidental overwriting of work.  Say I've gone and made a bunch of changes in the script pane, but switch over to the JSON pane to check an old value.  If I press save (this is reflexive for more devs, and really easy to do now thanks to the new editor button shortcuts) while on the JSON pane, I overwrite all of my changes on the other panes.

This is particularly bad because it's backwards-incompatible from a workflow standpoint; users that were used to not having JSON save behaviour will not be expecting this to happen.

**Comment by Wolvan** [comment]
Hmm, that's a good point. What do you suggest in this case, @0xazure?

**Comment by 0xazure** [comment]
Couple solutions I came up with off the top of my head:

- Have a save confirmation popup when a user saves, maybe only when the JSON pane is active
- Implement live updating of the panes.  I.e. If you make an edit on the script pane, this change is immediately reflected on the JSON pane without requiring a save

I won't say "do it this way" because I really don't know.  I just wanted to point out the problem; how you solve it is really up to you.

**Comment by Wolvan** [comment]
@0xazure updating automatically if you change something would be really good, how much performance impact would it be if we hook an keydown event?

**Comment by 0xazure** [comment]
I guess it would be as performant as `JSON.stringify()`/`JSON.parse()` in the browser.  Probably not _too_ bad, considering most XKit extensions aren't all that large to begin with.

**Comment by Wolvan** [comment]
@0xazure I decided on a warning message that occurs if you changed something but are on the wrong tab since keydown and parsing completely lagged out the textarea in my browser

**Comment by 0xazure** [comment]
@homu r+

**Pull request merged**
