### PR TITLE
[WIP] Re-implement build tasks in Gulp.js

### LINKED ISSUE #163: grunt clean removes npm dependencies
Per comments on #75 ([this one specifically](https://github.com/new-xkit/XKit/pull/75#issuecomment-126779126)) `grunt clean` is slightly borked and removes the `node_modules/` folder, which means subsequent `grunt` tasks cannot be run.

`grunt clean` currently necessitates a re- `npm install`: because of how Grunt runs multi-tasks, it runs the sub-task `clean:modules` as well as everything else defined under the `clean` task and blows away `node_modules/` in addition to the other folders to be cleaned.  As such, it should never be run directly. 

As a temporary work-around, run `grunt clean:releases` instead of the bare `grunt clean`.

I don't know how many this issue affects, and it's probably super-low priority, but I wanted to document it if anyone has similar questions to those in #75.

@0xazure will take ownership of this (since I can't self-assign).

### PR DESCRIPTION
**Pull request by 0xazure**
Back [when I first implemented build scripts](https://github.com/atesh/XKit/pull/167) for this project, there weren't many options for task runners.  I had settled on [Grunt](http://gruntjs.com/) simply because there weren't any other reasonably mature task runners around.  Since then, we've had a veritable explosion of options, each approaching the problem in a different way.

After some tentative probing on Gitter, I found that none of the current core maintainers seem to have a preference for one task runner over another, as most don't have experience with any of the options available.  From this, I've gone ahead and reimplemented the build scripts in [Gulp.js](http://gulpjs.com/).

I find Gulp to be a better option for this project than Grunt for a number of reasons:

* It's much harder to make silly mistakes like #163 since Gulp has no notion of sub-tasks
* Gulp is [based on streams](http://maxogden.com/node-streams.html#why-streams), and so doesn't leave build artifacts behind (unlike Grunt) because all the operations Gulp performs modify the in-memory data and only writes to the filesystem [when explicitly instructed to do so](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpdestpath-options).
* With Gulp, all of the instructions live in the task code, whereas Grunt relies on configuration objects in addition to task code to instruct tasks how to do their job (you can see this [in our own `Gruntfile.js`](https://github.com/new-xkit/XKit/blob/b3d23843df40f2075148e4a5a77fa6f7dd9fd4b1/Gruntfile.js#L50-L169)).  This can make task comprehension more difficult, as there is more cognitive load in Grunt's split of task code and configuration objects.
* In my experience, Gulpfiles are typically shorter and easier to understand than Gruntfiles.  Compare the `gulpfile.js` in this PR to [what we currently have](https://github.com/new-xkit/XKit/blob/b3d23843df40f2075148e4a5a77fa6f7dd9fd4b1/Gruntfile.js) and you'll see a significant line number reduction while implementing the same tasks.

## Implemented in this PR:

* Complete re-implementation of the old Grunt tasks as Gulp tasks
  * Fixes #163
* Updated 'Develop XKit' info in the README
* A project-level [EditorConfig](http://editorconfig.org/) file to help maintain style across contributors
* [JSCS](http://jscs.info/) linting and reporting for code style
* [CSSLint](https://github.com/CSSLint/csslint) linting and reporting for CSS files
  * **NB**: CSS linting is currently not included in the `lint` task by default, there are way too many errors for it to be useful for CI right now
* Remove outdated `build.sh` and Grunt-related code
* Dropped support for building Safari releases (as per #77)

#### `gulp` (default)

The default task.

See also: `gulp lint`.

#### `gulp watch`

Watches filesystem and lints files on change.

See also: `gulp lint:scripts`, `gulp lint:css`.

#### `gulp clean`

Top-level cleaning task.

See also: `gulp clean:build`.

#### `gulp clean:build`

Cleans the `build/` directory, deleting it and any subfolders.

#### `gulp clean:modules`

Cleans the `node_modules/` directory, deleting it and any subfolders.

#### `gulp clean:chrome`

Cleans the `build/chrome/` directory, deleting the previous build for Chrome.

#### `gulp clean:firefox`

Cleans the `build/firefox/` directory, deleting the previous build for Firefox.

#### `gulp lint`

Top-level linting task.

See also `gulp lint:scripts`, `gulp lint:css`.

#### `gulp lint:scripts`

Lints JavaScript files using JSHint and JSCS, and reports the output.

#### `gulp lint:css`

Lints CSS files using CSSLint and reports the output.

#### `gulp build`

Top-level build task.

See also: `gulp build:chrome`, `gulp build:firefox`.

#### `gulp build:chrome`

Builds the Chrome browser extension from source and outputs it to `build/chrome/`.  Also creates an archive, `new-xkit-x.x.x.zip`, and outputs it to `build/chrome/`.

#### `gulp copy:chrome`

Builds the Chrome browser extension from source and outputs it to `build/chrome/`.

See also: `gulp build`, `gulp build:chrome`, `gulp compress:chrome`.

#### `gulp compress:chrome`

Creates an archive, `new-xkit-x.x.x.zip`, from an existing Chrome source build and outputs it to `build/chrome/`.

See also: `gulp build`, `gulp build:chrome`, `gulp copy:chrome`.

#### `gulp build:firefox`

Builds the Firefox browser extension from source and outputs it to `build/firefox`.  Also creates a [Cross-platform Installer Module](https://developer.mozilla.org/en/docs/XPI), `@new-xkit-x.x.x.xpi`, and outputs it to `build/firefox/`.

See also: `gulp compress:firefox`, `gulp copy:firefox`.

#### `gulp copy:firefox`

Builds the Firefox browser extension from source and outputs it to `build/firefox/`.

See also: `gulp build`, `gulp build:firefox`, `gulp compress:firefox`.

#### `gulp compress:firefox`

Creates a [Cross-platform Installer Module](https://developer.mozilla.org/en/docs/XPI), `@new-xkit-x.x.x.xpi`, from an existing Firefox source build and outputs it to `build/firefox`.

See also: `gulp build`, `gulp build:firefox`, `gulp copy:firefox`.

## Feedback:

I'd love to hear thoughts on this PR.  I'd especially like to know:

* [ ] Am I missing any common tasks we don't have automation for?
* [ ] Does the task organization make sense? (i.e. `gulp build[:<platform>]` vs. some other format)
* [ ] Is there anything that isn't well documented?

as well as anything else!

I also specifically need another sanity check on the builds that get produced to confirm they work as expected.

---

#### Post-merge TODO:

* [ ] Move the above documentation on Gulp tasks over to the wiki
* [ ] Update the README with a proper link to the above wiki page

### CODE REVIEW

**Comment by 0xazure** [comment]
The JSCS checks are currently causing linting to fail.  It's all '_Mixed spaces and tabs_' warnings from Extension files, should I include those changes in this PR as well?

**Comment by bvtsang** [comment]
Including the fixes to mixed tabs and spaces in this pull request would be good!

**Comment by 0xazure** [comment]
@hobinjk is `xkit.xpi` the right name for the Firefox archive, or is it supposed to be called something else?

**Comment by hobinjk** [comment]
@0xazure The xpi can be called anything, although the way it is generated is with Firefox's Jetpack Addon SDK. This generates an `install.rdf` file from `Firefox/package.json`. The directory structure to recreate in the xpi is:
```
  inflating: README.md
  inflating: bootstrap.js
  inflating: index.js
  inflating: package.json
  inflating: install.rdf
  inflating: icon.png
  inflating: data/bootstrap.js
  inflating: data/bridge.js
  inflating: data/storage.js
  inflating: data/xkit/jquery.js
  inflating: data/xkit/editor.js
  inflating: data/xkit/moment.js
  inflating: data/xkit/nano.js
  inflating: data/xkit/tiptip.js
  inflating: data/xkit/xkit.css
  inflating: data/xkit/xkit.js
```
And the generated install.rdf is
```xml
<?xml version="1.0" encoding="utf-8"?>
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:em="http://www.mozilla.org/2004/em-rdf#">
    <Description about="urn:mozilla:install-manifest">
          <em:id>@new-xkit</em:id>
          <em:type>2</em:type>
          <em:bootstrap>true</em:bootstrap>
          <em:unpack>false</em:unpack>
          <em:version>7.7.0</em:version>
          <em:name>New XKit</em:name>
          <em:description>Fork of XKit, the Tumblr extension framework</em:description>
          <em:creator/>

          <em:targetApplication>
            <Description>
              <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
              <em:minVersion>35.0</em:minVersion>
              <em:maxVersion>39.0</em:maxVersion>
</Description>
</em:targetApplication>

          <em:targetApplication>
            <Description>
              <em:id>{aa3c5121-dab2-40e2-81ca-7ea25febc110}</em:id>
              <em:minVersion>35.0</em:minVersion>
              <em:maxVersion>39.0</em:maxVersion>
</Description>
</em:targetApplication>
    </Description>
</RDF>
```

**Comment by 0xazure** [comment]
Finished appeasing JSCS.

@hobinjk okay, I'll have to have another look at how we build the Firefox extension then.  I had assumed from a cursory glance over the docs that it was just a simple `.zip` archive.

**Comment by nightpool** [comment]
@0xazure basically, you should shell out to jpn build, which constructs the
xpi. (however that is done idiomatically within gulp)

**Comment by hobinjk** [comment]
@nightpool I think all jpm is doing is zipping the contents of the Firefox directory with the install.rdf I showed. I believe that we can replace package.json with the generated install.rdf and remove our dependence on `jpm`

**Comment by nightpool** [comment]
@hobinjk we also need the auto-generated bootstrap js which we can copy
from https://github.com/mozilla/jpm-core/blob/master/data/bootstrap.js
<http://here>

I don't know if this seems more or less fragile then trying to shell out to
jpm though. :/

**Comment by 0xazure** [comment]
Based on my picking apart [mozilla/jpm](https://github.com/mozilla/jpm), the executable's doing a few things:

1. parsing the `package.json` at the project root ([here](https://github.com/mozilla/jpm/blob/master/lib/utils.js#L81), called from [here](https://github.com/mozilla/jpm/blob/master/lib/cmd.js#L14))
2. merging the mainfest keys with some defaults ([here](https://github.com/mozilla/jpm/blob/master/lib/xpi.js#L35-L42))
3. generating the `boostrap.js` file ([here](https://github.com/mozilla/jpm/blob/master/lib/xpi.js#L41))
4. validating the manifest  ([here](https://github.com/mozilla/jpm/blob/master/lib/validate.js), called from [here](https://github.com/mozilla/jpm/blob/master/lib/xpi.js#L50))
5. building the `install.rdf` file from the manifest ([here](https://github.com/mozilla/jpm/blob/master/lib/rdf.js#L21-L135), called from [here](https://github.com/mozilla/jpm/blob/master/lib/xpi/utils.js#L80), called from [here](https://github.com/mozilla/jpm/blob/master/lib/xpi.js#L55))
6. zipping the Extension files into an archive ([here](https://github.com/mozilla/jpm/blob/master/lib/xpi/utils.js#L103), called from [here](https://github.com/mozilla/jpm/blob/master/lib/xpi.js#L59))

There are a few other minor things, but that's basically the gist of it.

It would certainly be feasible to ditch the dependency on `jpm`, it would just require writing a new module to handle the work and then plugging it into the `gulp build:firefox` task.  The only sort-of _proprietary_ (read: Mozilla-y, Firefox extension-specific) steps are 3 and 4, and those are both implemented as external modules themselves.

I think for now it's better to leave in the `jpm` dependency and explore a replacement at a later date.  Considering the work that would go into re-implementing what `jpm` does, I think we can live with a slightly less robust option of shelling out to an executable.

**Comment by nightpool** [comment]
@0xazure I think the point @hobinjk is making is that all of that, except
zipping the archive, is expected to be constant from version to
version—therefore, we don't need to reimplement the process that creates
install.rdf, as long as we have one in tree that we bump for version
numbers and stuff. (does that make sense from what you've seen?)

**Comment by 0xazure** [comment]
Sure, if committing an `install.rdf` is something we want to do, that's fine, we can template it in `Firefox/` and inject the data that changes from our `package.json` or something.

The only data that should be changing is `<em:version/`> (our extension versioning), and `<em:maxVersion/>` for the two engines we target (I don't actually know what the point of this key is, because [the npm version of `jpm`](https://github.com/mozilla/jpm/blob/master/lib/settings.js#L11) is behind [what Mozilla claims is current](https://addons.mozilla.org/en-US/firefox/pages/appversions/)).

Give me some time to play around with it and I'll see what I can come up with.

**Comment by 0xazure** [comment]
In the interim, pushed updates to properly build archives for both Chrome and Firefox.  I've updated the PR; a summary of the changes is below:

* Reconfigured `gulp build:chrome` to include creating an archive.
* Improved `gulp build:firefox` to build the XPI by shelling out and using `jpm`.

**Comment by hobinjk** [comment]
Looks good to me. Any objections to merging this and leaving replacing `jpm` to a future issue?

**Comment by hobinjk** [comment]
Tested this locally and everything works perfectly! The JSCS compliance changes also look good.  I think removing `jpm` would be a fun technical challenge, but not actually worth anything from a UX perspective, so it can be shelved for the foreseeable future.

@homu r+

**Comment by 0xazure** [comment]
Wasn't expecting a merge quite so soon, but if everything looks good, I'm all for it.

Agreed on shelving the `jpm` item.  Shelling out works for now, and the bin gets installed from `package.json`, so it's all bundled together.  I may add an issue to the backlog, just so we have a record.

I'll move the build task docs to the wiki and update the README once that's done.

**Comment by hobinjk** [comment]
It looks like I spoke too soon and the `.editor_config` isn't entirely correct: https://github.com/new-xkit/XKit/commit/6e4de3014ea1ba0c9c8f1f6cf4292df063b1e965#commitcomment-12604756

**Pull request merged**
