### PR TITLE
Implement Safari build tasks

### LINKED ISSUE #546: Implement Safari build tasks
In preparation for the re-release of the Safari version, implement Gulp build tasks for extension building.

### PR DESCRIPTION
**Pull request by 0xazure**
Progress towards #572.

Closes #546.

### CODE REVIEW

**Comment by 0xazure** [comment]
Post-merge TODOs:

- [ ] Document changes to `gulp build`
- [ ] Document safari tasks

**Comment by finagle29** [comment]
I'm thinking the Safari build task should create a new-xkit-{version}.safariextension folder inside /build/safari similar to how there's a new-xkit-{version}.zip in /build/chrome and a @new-xkit-{version}.xpi in /build/firefox.

**Comment by 0xazure** [comment]
Yes, I realized that I forgot to check the folder syntax Safari is expecting for unpacked extensions.  I'm also going to play around with [xar-js](https://www.npmjs.com/package/xar-js) and see if we can build an unsigned `.safariextz` archive for dev testing.

**Comment by 0xazure** [comment]
Changed my mind about building archives.  Simply loading the `build/safari.safariextension/` directory into the Safari Extension Builder affords us 'reload' functionality.  If we bundled up an archive, we would have to keep uninstalling and reinstalling the extension.

Also, since Apple requires us to sign the extension _before_ making it widely available (in contrast to Mozilla and the Firefox extension store, where they sign our extension _after_ we've uploaded it to them), generating a `xar` archive programatically right now isn't feasible given the sensitivity of the certificate files required.

**Comment by 0xazure** [comment]
Probably should have noted:  PR code has been updated to generate the `.safariextension`-suffixed build directory required by Safari's Extension Builder.  Why they insist on an arbitrary pseudo-extension on a directory I will never know.

**Comment by finagle29** [comment]
`gulp lint:scripts` should probably also lint `Safari/**/*.js`

**Comment by hobinjk** [comment]
Just used this locally to build and test changes to the extension and it LGTM. Definitely want the linting added though

**Comment by 0xazure** [comment]
Updated to include `Safari/**/*.js` in `gulp lint:scripts`.

**Comment by finagle29** [comment]
With linting added (and JSHint warnings fixed), this LGTM too
@homu r+

**Pull request merged**
