### PR TITLE
bump version on patches

### LINKED ISSUE #686: New change to Tracked Tags
Yesterday the tracked tags would show a number showing how many new posts are in the tags. Also when you clicked on them it would go to the page using the "classic search" extension (if you had it)
Today they changed it, the numbers no longer show up and the page once clicked no longer use the "Classic search" extension meaning you have to click on the search bar and hit enter for the extension to apply.
tumblr1
tumblr2

### PR DESCRIPTION
**Pull request by nightpool**
we forgot to do this in #704 @jwbay @Wolvan 

fixes #686

### CODE REVIEW

**Comment by hobinjk** [comment]
Something happened to make this a +2034,-2034 rewrite of the file

**Comment by nightpool** [comment]
@hobinjk web editor

**Comment by 0xazure** [comment]
Fixed the weird diff, bumped the version one `PATCH` level.

**Comment by nightpool** [comment]
bae @homu r+

**Pull request merged**
