### PR TITLE
Add option for background colors for reblogs

### PR DESCRIPTION
**Pull request by lizzledpink**
For differentiating between OP, reblogs, and your followers' comments

### CODE REVIEW

**Comment by ThePsionic** [comment]
This sounds more of an option for Reblog Display Options than for Tweaks.

**Comment by lizzledpink** [comment]
Ah, good point

**Comment by nightpool** [comment]
pretty sure there is already a nested option that got carried over from
color quotes that does this.

an addition to flat to support this would be great

**Comment by lizzledpink** [comment]
Yeah, sorry, I don't use RDO myself so it slipped my mind that it exists, implementing as a flat option now

**Pull request closed without merging**
