### PR TITLE
Fix Go To Dash 'View' button

### LINKED ISSUE #1014: On-Blog icons are semi-broken.
ss 2016-04-09 at 06 01 46

At least this is what it looks like to me. (Chrome-user)

### PR DESCRIPTION
**Pull request by yanyi**
Fixed Go To Dash 'View' button previously messing up the iframe. Fixes #1014.

Used the old jQuery style of setting the Dashboard text as empty as I could not find documentation on how to use `XKit.iframe.hide_button();`

### CODE REVIEW

**Comment by nightpool** [comment]
Hey! This looks great, thank you! Unfortunately, we should do something a little more to fix the hide_button function in xkit_patches. Can you take care of that?

Thanks!

**Comment by nightpool** [comment]
Also, you need to rebase or squash any merge commits, thanks!

**Comment by yanyi** [comment]
Hey @nightpool, sorry, I was actually waiting for you to reply on my code changes. Didn't know if I was doing it right since it's my first time making pull request.

**Comment by nightpool** [comment]
Currently your PR has 2 junk merge/revert commits and a change to the unrelated "bookmarker" extension, and it needs to be rebased against master so I can merge it. You can read more about rebasing here: https://www.atlassian.com/git/tutorials/rewriting-history/

I'll take a look at both this or #1038 when I get a chance and integrate something that makes sense. Thanks for the contribution!

**Comment by yanyi** [comment]
@nightpool I read through the tutorial and went ahead with an interactive rebase that `drop` the previously unneeded commits to clean it up. Then I rebased it against the XKit's master. Could you please advise me if I have done it correctly?

**Comment by nightpool** [comment]
Looks great. I don't have time to test these two until tomorrow or tonight,
but thanks for the quick response!

(also, feel free to drop by our gitter chat
<https://gitter.im/new-xkit/xkit> sometime and hang out and talk about dev
stuff!)

**Comment by yanyi** [comment]
Alright, sure thing. Would love to learn more! Thank you!

**Comment by nightpool** [comment]
Looks good to me @homu r+

**Pull request merged**
