### PR TITLE
Adding logic to handle chat posts on viewondash

### PR DESCRIPTION
**Pull request by blackjackkent**
No associated issue. It's just broken. :P

### CODE REVIEW

**Comment by nightpool** [comment]
I'd prefer to stop supporting view on dash in favor of the new in-dash
viewer. thoughts?

**Comment by Wolvan** [comment]
@nightpool :-1: Some people have the peeper disabled through open in tabs, they can't use it

**Comment by nightpool** [comment]
@wolvan how would open-in-tabs disable the /dashboard/blog/ urls? that
doesn't make any sense.

**Comment by Wolvan** [comment]
/dashboard/blog/? I thought we were talking about Peepr

**Comment by nightpool** [comment]
@wolvan what would you call this
<http://tumblr.com/dashboard/blog/new-xkit-extension> except peepr?

**Comment by Wolvan** [comment]
OK, so it is the peepr, it's still rather inaccessible. We could just make view-on-dash, instead of generating the posts ourselves, open the peepr. No need to completely remove View-on-dash

**Comment by nightpool** [comment]
@wolvan that's what I meant, sorry.

**Comment by Wolvan** [comment]
Oh, sorry. In that case, :+1:

**Comment by hobinjk** [comment]
View On Dash's possible replacement by Peepr should be filed as a separate issue. This functionality LGTM.

@homu r+

**Pull request merged**
