### PR TITLE
Add icon for Show Picture Size

### PR DESCRIPTION
**Pull request by ThePsionic**
It's 1AM and I have nothing better to do

### CODE REVIEW

**Comment by Wolvan** [comment]
Don't forget to version bump. I like it though

**Comment by nightpool** [comment]
What does this look like in the gallery / options panel? Not sure how many other XKit icons are grey/black...

**Comment by Wolvan** [comment]
image
posted this on gitter, but here again for reference. I personally don't mind it.

**Comment by nightpool** [comment]
Other ways this trips my ":

- its not centered like all of the other ones
- there's much less padding on it
- its a little more cluttered then others, there's a lot of detail happening there (internal padding can play a role here, as well as less detail on the "photo" graphic)

**Comment by Wolvan** [comment]
Honestly, @nightpool, I don't think either of these apply. Or rather I may just not see it or it doesn't bother me, so I can't really follow your points here
Is that some kind of objective thing that you are talking here which I don't know about regarding icon design?

**Comment by ThePsionic** [comment]
Moved around some bits and added a dash of color, maybe @nightpool likes this more :P (not committed yet, though)

**Comment by ThePsionic** [comment]
Final attempt for tonight to please the @nightpool

**Comment by ThePsionic** [comment]
Closing since I'm sure @shutterspeak will do a much better job when they get around to it

**Pull request closed without merging**
