### PR TITLE
Tweaks: Fix some titles not being classic-ified

### LINKED ISSUE #439: Tweak to reduce size of post titles is no longer working.
Probably related to Tumblr dashboard style updates.

### PR DESCRIPTION
**Pull request by ThePsionic**
Fixes #439

### CODE REVIEW

**Comment by Wolvan** [comment]
LGTM
@homu r+

**Comment by ThePsionic** [comment]
Forgot to bump the version so will be deployed when #446 goes through

**Comment by nightpool** [comment]
#446 does not bump tweaks.

I'll pushed an update to master and then deploy.

**Comment by Wolvan** [comment]
@nightpool wait
Actually, #446 does bump tweaks to 4.0.4

**Comment by nightpool** [comment]
@Wolvan huh. in my face! that was unintentional haha I'm going to un-commit it.

**Comment by Wolvan** [comment]
Don't do it, that way we can fix 2 things at once

**Comment by nightpool** [comment]
@wolvan it was a useless typo. and i've already bumped and deployed this PR.

**Comment by Wolvan** [comment]
@nightpool Ah, ok. Continue then

**Pull request merged**
