### PR TITLE
Deprecate `XKit.lang`

### LINKED ISSUE #716: Depreciate XKit.lang
XKit has never really supported proper localization (l18n), and usage of `XKit.lang` seems to be localized to a [commented-out block in `one_click_postage.js`](https://github.com/new-xkit/XKit/blob/55943a7164615141acbb6b0180571d44b5160206/Extensions/one_click_postage.js#L1537-L1539) and a smattering in `xkit_preferences.js` ([as an example](https://github.com/new-xkit/XKit/blob/55943a7164615141acbb6b0180571d44b5160206/Extensions/xkit_preferences.js#L678-L683)).

We should probably look at cleaning up this old attempt before investigating proper l18n.

### PR DESCRIPTION
**Pull request by 0xazure**
Remove references to `XKit.lang` methods and language packs.

Fixes #716.

### CODE REVIEW

**Comment by nightpool** [comment]
I'm fine with making this a minor because lang packs were never user facing.

**Comment by 0xazure** [comment]
I debated the version bumping, but a strict reading of SemVer makes this a `MAJOR` since functionality is being removed, regardless of if it was user-facing.

**Comment by hobinjk** [comment]
LGTM with merge conflicts resolved.

**Comment by 0xazure** [comment]
Updated.  Only conflict was the `VERSION` string in `xkit_preferences.js`. :confused:

**Comment by Wolvan** [comment]
It's literally always the god damn VERSION, isn't it?
But since the merge conflict is resolved and @hobinjk says it looks good:
@homu r=hobinjk

**Comment by Wolvan** [comment]
and there goes my PR again as well

**Pull request merged**
