### PR TITLE
Move update.rdf to central location

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by 0xazure** [comment]
What's the reason for moving the update file?

**Comment by hobinjk** [comment]
`Extensions/dist/page` seemed like a better location for files that will eventually be automatically generated.

**Comment by nightpool** [comment]
@homu r+

but eventually we should separate all of our hosted stuff out into a separate new-xkit.github.io repo IMHO

(@wolvan will travis push this as an update? or will we have to do this manually?)

**Comment by Wolvan** [comment]
@nightpool this should autoupdate I believe,

**Pull request merged**
