### PR TITLE
Allow rounded user icons in chat

### PR DESCRIPTION
**Pull request by Wolvan**
As requested, this messaging tweaks allows the icons in the chat to be
round, similar to what Skype 7 does with user's icons in chat. It also
allows the icons to transition to the rectangular form on hovering over
them

### CODE REVIEW

**Comment by finagle29** [comment]
Tested and works, maybe think about adding something to note that the second option only does something if the first one is enabled (e.g. change wording to "Make round icons rectangular on hover")

**Comment by nightpool** [comment]
maybe disable the second option if the first one isn't enabled?

**Comment by Wolvan** [comment]
@finagle29 I did what @nightpool suggested and just hide the setting when the rounded icons are disabled

**Comment by finagle29** [comment]
tested and works LGTM @homu r+

**Pull request merged**
