### PR TITLE
Add quote restyling option to Tweaks

### LINKED ISSUE #883: Paragraph and line breaks not working in Quote posts on the dash
I've got a problem where if I make a quote post, especially if it's a poem or something where I've divided the text down to several short lines, the paragraph breaks won't show up on the dashboard. The first verse of a poem might have a working paragraph break after it, but then all the other verses that come after it will be just one long column of text. (The post will look fine when I'm on my blog page, however--this only happens on the dashboard, and when I go in to edit the post, it has put in the HTML for </br> and </p>.) I've had a similar problem with old text posts recently as well and it's even worse: even the line breaks disappear, and they get mushed into just one big wall of text, and that happens on the blog pages themselves as well. I know Tumblr has always had stupid issues with paragraph breaks, but this seems to be a new one. Anyone else seen it?

### PR DESCRIPTION
**Pull request by radialarch**
- css to force quotes posts with paragraph tags to display normally, because tumblr squashes their formatting

basically from this:
quotes before

to this:
quotes after

ETA: welp i wrote this because it was annoying me & pr'd bc i just didn't want it to get nuked if tweaks updates, but it might fix #883, now that i'm looking

### CODE REVIEW

**Comment by hobinjk** [comment]
Slight nitpick: The version should be 2.3.0 instead of 2.3.2. Otherwise LGTM, great work!

**Comment by radialarch** [comment]
ah, i don't know how versioning works /o\

fixed!

**Comment by nightpool** [comment]
I'd prefer to fix this on the submission end, so people don't have to be using XKit to see the correct behavior. Can we add some sort of listener instead? The workaround i've been using is adding non-breaking spaces between all of my paragraphs.

**Comment by radialarch** [comment]
@nightpool you mean add them to the post right when you're creating one? how does that work out for quote posts with more than two paragraphs? (tumblr only renders the first & last paras as inline-block, right) and does it affect how the post displays on people's themes when they reblog?

**Comment by nightpool** [comment]
@radialarch so, the fact that tumblr doesn't respect paragraph breaks is a bug, right? You can get around that by forcing full lines between each quote paragraph, using a non-breaking space entity.

**Comment by radialarch** [comment]
@nightpool well so when you say "fix on the submission end" you mean you want to use xkit to add the nbsp lines when a post gets published, right? so people who aren't using xkit will can still see the breaks when it comes around on their dash?

so like, here's a four-paragraph quote post on my dash without any external manipulation 
(the paragraphs start with "Perhaps", "Not", "Let's", and "Risky"):
unstyled quote raw

this is what it looks like with `&nbsp;` after every paragraph:
unstyled quote nbsp
i.e. the one after the first paragraph and before the last one get absorbed into the paragraph because they're still displaying as inline-block

otoh, if it's `<p>&nbsp;</p>`:
unstyled quote p nbsp
because tumblr, for some bizarre reason known to no one, literally gives only the second paragraph of quotes a 10px top margin, so the space between those first two paragraphs ends up being bigger than the space between all the other paragraphs. (??? why tumblr)

which is irritating but i could live with it, maybe, except my other concern is how does this post then display on people's themes. so a post that originally displays like this (i.e. correctly):
theme orig

is gonna look like this instead:
theme nbsp

so i guess my question is, is the tradeoff (having the posts display okay-ish on the dashboards of people without xkit) worth introducing the extra spacing on people's blogs proper, depending on what kind of theme they have?

**Comment by nightpool** [comment]
i'd say yeah, personally. its how I format all my text posts now. or you
could just bug tumblr support about it.

**Comment by radialarch** [comment]
tumblr support are only giving me a non-answer & zero actual tech support /cries about it

**Comment by nightpool** [comment]
Okay, I'll follow up with Tumblr Support about this personally, and try to get a straight answer out of them. This is a *very* broken part of the dashboard, and it's also inconsistent between desktop and mobile, so they can't really get away with calling it a problem on our end.

I'll close this pending resolution from Tumblr. Depending on what answer I get from support I'll consider either reopening this or evaluating other options

**Pull request closed without merging**
