### PR TITLE
Add tweaks for new reblog styles

### PR DESCRIPTION
**Pull request by nightpool**
one adds a margin to posts, one decreases the padding a little

### CODE REVIEW

**Comment by Wolvan** [comment]
this looks good to me, can you give us a screenshot (for the people who don't have the update yet, like me)?

**Comment by nightpool** [comment]
yah here's an imgur album I made for inclusion in the update post:
http://i.imgur.com/N9HdvVS.png
http://i.imgur.com/N9HdvVS.png
,h2wO0L6,kEhLYix

**Comment by nightpool** [comment]
Yeah, here's an imgur album I made for the announcement post:

**original:**

<hr>
**compressed:**

<hr>
**compressed with margins:**

**Comment by Wolvan** [comment]
Can you maybe remove the spacing in the compressed with margin between the user url and the text?

**Comment by nightpool** [comment]
I considered that, but that's where the user icon is. So not unless I do something else with that

**Comment by Wolvan** [comment]
I got that, but if you look at the picture with the margin, wouldn't it be nice to have the comment closer to the userurl? It just looks wird with that much space if it already has the same margin as the url

**Comment by macleodsawyer** [comment]
I believe this should be a whole new extension, not hidden in tweaks.

The reason I say it needs to be a new extension is because although it is a 'tweak' its to change just the dashboard.

We need to change more than just the dashboard, i already submitted a pull request with an extension with a few different options with it.

**Comment by macleodsawyer** [comment]
+ Just added two more options, another reason why this should be an extension 

Extension can be found at #421

**Comment by nightpool** [comment]
going to merge this #426 and #421 into a single pull.

**Pull request closed without merging**
