### PR TITLE
Adding unfollow functionality to inactive tracker

### PR DESCRIPTION
**Pull request by blackjackkent**
There was discussion a week or two ago that we no longer have major objections to implementing this feature (as long as it's not an "unfollow all" button), so I went ahead and implemented it.

### CODE REVIEW

**Comment by nightpool** [comment]
supersedes #918?

**Comment by nightpool** [comment]
Sorry, #696

**Comment by blackjackkent** [comment]
Yes. Figured after two years it was easier to just do a clean new pull than try and untangle that one. :)

**Comment by nightpool** [comment]
sounds good

**Comment by nightpool** [comment]
LGTM. cool enough to draft a post about?

**Pull request merged**
