### PR TITLE
Add tweak to restore borders to asks

### PR DESCRIPTION
**Pull request by estufar**
I'd originally just made this as a [user style](http://estufarextensions.tumblr.com/post/132567682338/get-ask-borders-back), but @Wolvan suggested that I add it in tweaks too, so here it is.

### CODE REVIEW

**Comment by bvtsang** [comment]
Don't forget to increment the extension version.

**Comment by nightpool** [comment]
LGTM as soon as it has a extension version increase

**Comment by estufar** [comment]
One of these times I'll remember to increment the version to begin with, but so far I'm 0 for 2

**Comment by nightpool** [comment]
nice @homu r+

**Comment by nightpool** [comment]
in the future, its fine to squash small stuff like version changes.

**Pull request merged**
