### PR TITLE
Links-in-new-tab -- Adding preference to prevent  behavior outside the dash

### LINKED ISSUE #121: could you perhaps create an option in the open in new tabs extension so it wouldn't apply to blogs off the dashboard?
(From asks)

### PR DESCRIPTION
**Pull request by blackjackkent**
Enabled the preference by default; not sure if it should be the other way round. Open to comments on that. Also includes some spacing fixes for consistency.

Fixes #121 .

### CODE REVIEW

**Comment by blackjackkent** [comment]
Oh, awesome. :) Didn't know that; will make the switch. THanks!

**Comment by blackjackkent** [comment]
Updated!

**Comment by finagle29** [comment]
looks good to me! @homu r+

**Comment by hobinjk** [comment]
Sorry! I forgot to add you to the reviewer list, which hopefully is fixed now
@homu r=finagle29

**Comment by finagle29** [comment]
@hobinjk it's all good now! i was wondering why nothing seemed to be happening...

**Pull request merged**
