### PR TITLE
Bump Firefox version for immediate listing

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by nightpool** [comment]
r- needs to update the firefox update.rdf

**Comment by hobinjk** [comment]
Updated, good catch

**Comment by nightpool** [comment]
Will you also handle making the GH release? (Right now the update.rdf file is linking to a 404)

**Comment by hobinjk** [comment]
Yes, I can do that now

**Comment by hobinjk** [comment]
https://github.com/new-xkit/XKit/releases/download/v7.7.2/new-xkit-7.7.2.xpi should no longer be a 404

**Comment by nightpool** [comment]
LGTM 
@homu r+

**Pull request merged**
