### PR TITLE
Fix can_edit's logic

### LINKED ISSUE #368: Quick Tags broke (also No Recommended and Shorten Posts?)
>It looks like Quick Tags doesn't work in Drafts, not sure if this was intentional but I always used to edit my posts tags in the drafts :c

>The icon for Quick Tags that shows up at the bottom of posts just isn't there for me, and therefore impossible to use in that way. It was definitely working prior, but it's just disappeared? I'm on Google Chrome with Windows 8.

>(Chrome, windows 8 if that helps) Quick tags have disappeared from drafts and queue unless I go to the edit option. On dash they are still there though for reblogging. This happened within the last hour or two.

>Running Windows Run, Chrome 44, Current Xkit. Hide recommended blogs, quick tags, and shorten posts have stopped working for me. I have forced it to update, no avail.

### PR DESCRIPTION
**Pull request by hobinjk**
Fix #368

### CODE REVIEW

**Comment by Wolvan** [comment]
Version Bump?

**Comment by hobinjk** [comment]
Bumped version

**Comment by hobinjk** [comment]
Oh my god wrong version

**Comment by hobinjk** [comment]
Should be good to go at this point

**Comment by finagle29** [comment]
LGTM
@homu r+

**Pull request merged**
