### PR TITLE
Suggestion: Messaging Tweaks - left-align text in own bubbles that have been moved to the right

### PR DESCRIPTION
**Pull request by nobodysuspectsthebutterfly**
For the messaging tweaks, recommend to use this CSS:

 .messaging-conversation .conversation-message .message { text-align: left; } 

so that the "move your own message bubbles to the right" option doesn't right-align the text in those bubbles. This gives an appearance like the message interfaces of Skype, iOS, and all the Android devices I'm aware of. 

(If I'm putting this in the wrong place again, I apologize, but hitting the "add pull request" button on the new-xkit page compares with atesh's master by default, and there's no obvious way to add a request.)

### CODE REVIEW

**Comment by Wolvan** [comment]
You compared the wrong branches this time. But you have the right repository!

**Comment by nobodysuspectsthebutterfly** [comment]
Please tell me which ones I should compare? I'm new to GitHub, as if you couldn't tell. ;)

**Comment by Wolvan** [comment]
Did you make that change to messaging_tweaks.js in your repo already?

**Comment by Wolvan** [comment]
Closing this PR since this is more of an issue than a PR.
@nobodysuspectsthebutterfly you might wanna check in with us on gitter to get this done properly
https://gitter.im/new-xkit/XKit

**Comment by nightpool** [comment]
@nobodysuspectsthebutterfly you can read more about git and PRs here:

 - https://help.github.com/articles/set-up-git/
 - https://help.github.com/articles/fork-a-repo/
 - https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
