### PR TITLE
recommended posts and see more blogs are hidden on scroll

### PR DESCRIPTION
**Pull request by finagle29**
this should fix issues with recommended posts not being hidden because post_listener is being used to hide posts versus in #337 when the jquery was only called once

### CODE REVIEW

**Comment by Wolvan** [comment]
Why do we add CSS to each post instead of adding some global CSS for recommended posts?

**Comment by blackjackkent** [comment]
Also looks like this won't merge cleanly -- can you pull master into it and repush?

**Comment by nightpool** [comment]
Don't merge, rebase!

**Comment by blackjackkent** [comment]
^ yes. `git pull --rebase` the master branch

**Comment by finagle29** [comment]
@Wolvan it looks like tumblr has its own jQuery to add `display: block` on recommended posts if there's a global `display: none` and I wasn't sure what the consensus was on using `!important`, but adding CSS globally with `!important` does work

**Comment by nightpool** [comment]
@finagle29 important is fine if we're overriding tumblr styles.

**Comment by finagle29** [comment]
i think i did something wrong in command line git

**Comment by finagle29** [comment]
closing in favor of #348

**Pull request closed without merging**
