### PR TITLE
Update jquery to most recent 3.x version

### PR DESCRIPTION
**Pull request by hobinjk**
2.x -> 3.4.1

### CODE REVIEW

**Comment by hobinjk** [comment]
This was actually release in May 2019 so go jquery I guess? Definitely needs more testing and a thorough pass through the release notes of 3.x.0 where x != 0

**Comment by AprilSylph** [comment]
does jquery really not follow semver properly? we should only need to check the 3.0 upgrade guide for breaking changes

**Comment by nightpool** [comment]
not everyone follows semver, and even when they do "breaking changes" are a
matter of perspective

**Comment by hobinjk** [comment]
2.x -> 3.0. I'm still going to hit the minor releases just in case but I am feeling more trust than I did earlier

### Breaking change: .data() names containing dashes
.data() is always used with an argument so this doesn't apply

### Breaking change and Feature: jQuery.when() arguments
The one use of `.when` in classic tags expects it to behave like Promise.all, which it does

### Breaking change: jQuery.when() progress notifications
See above

### Breaking change: .width(), .height(), .css("width"), and .css("height") can return non-integer values

There's a borderline case in Drafts+ which has a === in a comparison but it appears to still behave correctly

### Breaking change: .outerWidth() or .outerHeight() on window includes scrollbar width/height
There are only two uses of outerHeight, both of which seem safe since there won't be scrollbars in the element

### Breaking change: .show(), .hide(), and .toggle() methods now respect more stylesheet changes
`.hide()` seems a little weird but the [giant compatibility table makes it seem like we're okay](https://docs.google.com/spreadsheets/d/1UaISjcS3UMxVJ7eSBIXtK-jqF8Grl67w640peCqlkoc/edit#gid=0)

### Breaking change: .load(), .unload(), and .error() removed
No longer present in codebase \o/

### Breaking change: .on("ready", fn) removed
Unused

### Breaking change: jQuery.event.props and jQuery.event.fixHooks removed
Unused

### Breaking change: Delegated events with bad selectors throw
If this were an error before then (hopefully) someone would have noticed, this will just make it easier to notice

### Breaking change: .wrapAll(function) only calls the function once
Unused

### Breaking change: Invalid input to the .offset() method
The one weird collection passed in is in Themes+ and appears to be innocuous

### Breaking change: Behavior of :hidden and :visible
All uses of these pseudoselectors are on normal elements uneffected by the change

### Breaking change: jQuery("#") and .find("#") are invalid syntax
This doesn't appear to occur anywhere unless specific attributes are intentionally set to "" instead of being undefined or a valid attribute

### Breaking change: jQuery.param() no longer converts %20 to a plus sign
Everything appears to not even have spaces or %20s. timestamps and read_more_now might be a little strange. github_issue is fine with any variation on + or %20

### Breaking change: .andSelf() removed, use .addBack()
Unused

### Breaking change: .removeAttr() no longer sets properties to false
Auto Scroll is the only extension to use this behavior but it still works in 3.4.1 so it's probably fine

### Breaking change: select-multiple with nothing selected returns an empty array
I couldn't find anything that looked particularly suspect between most uses of `val` being clearly on text boxes and there being no mentions of `<select multiple>`

### Breaking change: jQuery 3.0 runs in Strict Mode
It's not like we're passing code into jQuery for it to evaluate

### Breaking change: document-ready handlers are now asynchronous
Uses of `.ready` already expect this behavior, I wasn't able to find anything using the bare syntax

### Breaking change: jQuery.isNumeric() and custom .toString()
We don't define custom toStrings anywhere

### Breaking change: Deprecated .context and .selector properties removed
Nothing uses these properties. Themes+ looks like it uses .selector but it's actually just an isolated trash fire of a different kind

### Breaking change: Deprecated .size() removed
Unused

### Breaking change: Undocumented internal methods no longer exposed
Unused

### Breaking change: Return values on empty sets are undefined
Anything that was broken by the previous return `null` behavior will be just as broken with this

**Comment by hobinjk** [comment]
3.1: "We do not expect this release to have any breaking changes"
3.2: "There should be no compatibility issues if upgrading from jQuery 3.0+."
3.3: "There should be no compatibility issues if upgrading from jQuery 3.0+."
3.4: Radio elements: expected state in event handlers -> Retags already does the right thing, might not even apply

**Comment by AprilSylph** [comment]
@hobinjk just be sure to squash+merge this yourself so we can point the release to master and still get The Badge™

the 7.9.0 release having jquery 2 in the source code archive would be very silly

**Pull request merged**
