### PR TITLE
Firefox 7.7.8 update

### PR DESCRIPTION
**Pull request by hobinjk**
I should write a tool to automate this 🤔

### CODE REVIEW

**Comment by Wolvan** [comment]
I should write a bot to automate all this :thinking:

**Comment by nightpool** [comment]
expanding brain meme:

 - tie firefox RDF generation into the build system
 - write a bot to automatically make the PR for us
 - write a travis post_build hook
 - write a selenium script

**Comment by Wolvan** [comment]
xkit

Just remember that you asked for this, @nightpool

**Comment by nightpool** [comment]
what the fuck

**Comment by nightpool** [comment]
how can you do an expanding brain meme but do it BACKWARDS

**Comment by nightpool** [comment]
consensus from dev chat is that we'll sign this version and publish it as a "pre-release" on GH, but not promulgate it widely due to concerns about update fatigue

**Comment by Wolvan** [comment]
xkit

Oops

**Comment by nightpool** [comment]
image

**Pull request closed without merging**
