### PR TITLE
Fix recommended badges showing up again

### PR DESCRIPTION
**Pull request by ThePsionic**
Our good friends at Tumblr HQ decided the recommended post footers needed a different class. Luckily, we are happy to stand in their way.

### CODE REVIEW

**Comment by Wolvan** [comment]
when did that happen? Maybe just add the css-selector instead of replacing it imo

**Comment by ThePsionic** [comment]
@Wolvan Why? The old class can only create new problems if something we DON'T want to block suddenly gets that class.

**Comment by Wolvan** [comment]
because it seems to still block successfully for me

**Comment by ThePsionic** [comment]
@Wolvan Fair enough, added the old class back.

**Comment by Wolvan** [comment]
LGTM. I can't test myself but we had someone in the support chat earlier telling us that it's the right class.
@homu r+

**Pull request merged**
