### PR TITLE
Replace uses of demo key with XKit.api_key

### LINKED ISSUE #1083: Stop using Tumblr API demo key
It looks like you're using the demo key to access the Tumblr API. Can you please register a new app at https://www.tumblr.com/oauth/apps and use its key instead? You will see increasing amounts of 429s by continuing to use this key, and it may even eventually stop working entirely. Thanks.

### PR DESCRIPTION
**Pull request by hobinjk**
Fixes #1083

### CODE REVIEW

**Comment by nightpool** [comment]
Where did XKit.api_key come from?

**Comment by nightpool** [comment]
here is the main key: kZSI0VnPBJom8cpIeTFw4huEh9gGbq4KfWKY7z5QECutAAki6D

i'm going to generate two more for Blog Tracker and TagViewer because they're pretty popular.

**Comment by nightpool** [comment]
blog tracker: SGNopnlvTovnqk902dJIjDAvxcZgCDBlPzaaw310IQSupIzkHb

tagviewer: 5CIOyjHfcrNFlyEJl2D7vnoDTYqV30lNAUaSd4LJKoBFOZOmxp

**Comment by hobinjk** [comment]
Updated and squashed

**Comment by nightpool** [comment]
LGTM @homu r+

**Pull request merged**
