### PR TITLE
Add CSP Nonce to add_function's script tag

### LINKED ISSUE #994: Audio+ Pop-out player no longer controls
Clicking play/pause/exit does nothing
:sob:

### LINKED ISSUE #995: Tumblr's CSP breaks script injection in Firefox
It's `script-src https://www.tumblr.com https://secure.assets.tumblr.com https://assets.tumblr.com https://sb.scorecardresearch.com https://*.google-analytics.com https://*.cedexis.com https://*.cedexis-test.com 'unsafe-eval' 'nonce-BsRuxURLVk50IN3my8ETjha6znU' https://fc.yahoo.com https://s.yimg.com`

Note that it has 'unsafe-eval' but not 'unsafe-inline'. There's probably a one-liner to get Firefox to pretend 'unsafe-inline' is there. Chrome's default behavior is to allow 'unsafe-eval' by default for some reason.

extensions that need to be updated:
- [x] ~~add_function~~
- [ ] outbox
- [x] reblog_as_text (should probably just be nuked unless we want to fix this to reblog images/photosets/links/etc. (something we actually get a lot of requests for fwiw))
- [x] soft_refresh
- [ ] xinbox
- [x] xkit_patches.blog_get

### PR DESCRIPTION
**Pull request by hobinjk**
Tumblr is out to get us^H^H^H^H doing good things for security!
Unfortunately, Firefox also does a good thing for security which makes
this one sad. Tumblr's CSP blocks inline script tags as used by
add_function, unless those inline script tags have the correct nonce
attribute specified in the CSP header. This patch fixes this by
subjecting the page to a brief interrogation until it gives up the nonce
value. Fixes #994, and addresses most of #995

### CODE REVIEW

**Comment by nightpool** [comment]
will merge when rebased

**Comment by nightpool** [comment]
(question—should we also change the add_function of xkit.js?)

**Comment by nightpool** [comment]
Looks like outbox needs a fix too

**Comment by nightpool** [comment]
other extensions creating scripts:

 - outbox
 - reblog_as_text (should probably just be nuked unless we want to fix this to reblog images/photosets/links/etc. (something we actually get a lot of requests for fwiw))
 - soft_refresh
 - xinbox
 - other xkit_patches functions (blog_get)

**Comment by hobinjk** [comment]
Outbox and the other places where script tags get created should be separate and the patches should make them use add_function.

**Comment by nightpool** [comment]
sounds good @homu r+

**Pull request merged**
