### PR TITLE
Add multiprocess permission

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by hobinjk** [comment]
Oh wait this needs the bump to 7.7.5

**Comment by nightpool** [comment]
I think that if we want to do #1291, we should probably do it by unifying the chrome and firefox code.

**Comment by hobinjk** [comment]
Yes, after this is merged I can upload the XPI to addons.mozilla.org to get a signed copy for uploading to a release, then #1292 can be merged to get people automatically updating to the uploaded signed XPI.

Unifying is definitely the proper way to do #1291 and eventual Edge support

**Comment by hobinjk** [comment]
@homu r=nightpool

**Pull request merged**
