### PR TITLE
changes href indexOf, regexes, splicing to use XKit.interface.where()

### PR DESCRIPTION
**Pull request by finagle29**
Ignore the Aug 10 commits I am new to command line git and tried (unsuccessfully) to resolve conflicts, those won't change anything because of 965feea.

### CODE REVIEW

**Comment by bvtsang** [comment]
In timestamps.js, there's a line that goes `var href_parts = document.location.href.match(/https?:\/\/([^.]+)\.tumblr\.com/);`. Did you want to replace that with something like `XKit.interface.where().user_url` as part of this pull request?

**Comment by finagle29** [comment]
@bvtsang From what i can determine, that line parses the href of the permalink on a post, which is not something that XKit.interface.where() does.

**Comment by bvtsang** [comment]
We might be talking about different things. [This line](https://github.com/finagle29/XKit/blob/regex-fixes/Extensions/timestamps.js#L158) seems to be what you are describing, but I am referring to [this line](https://github.com/finagle29/XKit/blob/regex-fixes/Extensions/timestamps.js#L161).

On closer inspection, I'm not quite sure how the latter gets called. I've tried visiting the following pages:

- `/dashboard/`
- `/tagged/`
- `/search/`
- `/explore/`
- `/likes/`
- `/blog/username/`
- `/blog/username/drafts/`
- clicking on a tracked blog

And none of them trigger that code path.

**Comment by finagle29** [comment]
Oops yeah i misread your comment.
I also can't get the second code path to run, do you think maybe it should be commented out and see if any users complain about problems for a certain timeframe and then remove it if everything is good?

**Comment by bvtsang** [comment]
Apparently it was added in https://github.com/new-xkit/XKit/commit/1ca72e2129d4bc3b704f92450e49c38b2135484e.

@hobinjk Do you know how to get that code path to run?

**Comment by finagle29** [comment]
According to the commit message it looks that's supposed to run on blogs like username.tumblr.com

**Comment by bvtsang** [comment]
Dang, `XKit.interface.where().user_url` doesn't get populated on username.tumblr.com. Okay, scratch that plan.

The rest of your pull request looks good though.

**Comment by finagle29** [comment]
I'll save that for a separate PR.

**Comment by bvtsang** [comment]
Very well!

@homu r+

**Pull request merged**
