### PR TITLE
Make the Dashboard respond to changes in window size

### PR DESCRIPTION
**Pull request by BobbySig**
This is an extension that primarily hides the horizontal scrollbar until the window is actually too small for the content, rather than what tumblr does now (if you have a 1080p monitor, snap a tumblr window to half screen to see what I mean). It's based off a Stylish theme I wrote a while back called Adaptive Dashboard that does the same thing with some extra header tweaks (which aren't here because of Header Options). As of now, it hides the sidebar to keep from needing horizontal scrolling until the window is less than 645px wide. Turning that off might become an option later.

### CODE REVIEW

**Comment by Wolvan** [comment]
Works pretty nice apart from 
image
happening. It cuts of my icons in the top bar (if it doesn't for you it might be because I have centered header enabled in header options?) If that could be fixed that would be cool.

Also, not sure if this shouldn't just be a tweak instead of a whole new extension, but input is appreciated on that question.

**Comment by BobbySig** [comment]
Yeah, I remember coming across that. That is from the fixed width header option. I made changes that keep that from happening, but the changes were in Header Options and I wasn't sure whether adding them to this PR was a good idea. Should I copy those changes to Header Options and commit them here or something else?

**Comment by nightpool** [comment]
Hmm.. do those changes preserve the same behavior of header options?

If so, adding them would be great

**Comment by BobbySig** [comment]
The only thing I did to header options to make the fixed width setting stop cutting off the icons was changing classic_header.js line 83's CSS from this:
```css
#search_query,
.search_form_field,
.search_form_row {
  width: 150px !important;
}
.ui_search {
width: 160px !important;
}
.l-header {
  width: 925px !important;
  min-width: 925px !important;
}
.l-header.l-fixed-header {
  width: 925px !important;
}
```
to this:
```css
.l-header {
  max-width: 925px !important;
}
.l-header.l-fixed-header {
  max-width: 925px !important;
}
```
It removes the restrictions on the width of the search box so it fills the available space, and stops forcing a minimum width on the header. Is that changing too much for this?

**Comment by BobbySig** [comment]
As for whether or not this should be in Tweaks, I'm really not sure. However, I've been kind of creeping on the issues page for a few weeks as I was debating if I wanted to make an extension (sorry...), so I'm somewhat aware of the current issue with Tweaks getting harder and harder to deal with as it keeps growing. Heck, Tweaks is the main reason I'm considering somehow allowing the search box in the extensions panel search through the text of the settings. Considering that, I'm not sure if putting it there and making it even more bloated is a great idea, especially with v8.0.0 and the Firefox madness happening so fast.

**Comment by Wolvan** [comment]
Tweaks was more or less supposed to be for all the "small" misc changes to tumblr that make it nicer to use. The problem with it being bloated stems from tweaks that should be in other extensions

**Comment by BobbySig** [comment]
...yeah, this could absolutely be small enough for a tweak. I'll move it over there. @nightpool should I also add the tweak I made in header options?

**Comment by Wolvan** [comment]
Don't forget to version bump tweaks!

**Comment by BobbySig** [comment]
*facepalm* Dangit. I'm thinking minor version rather than patch. Sound good?

**Comment by Wolvan** [comment]
You're adding a new feature, so yes, Minor version it is

**Comment by BobbySig** [comment]
Done.

**Comment by Wolvan** [comment]
LGTM, @homu r+

**Pull request merged**
