### PR TITLE
Update FirefoxUpdate.rdf to 7.7.5

### PR DESCRIPTION
**Pull request by hobinjk**
Should be landed after #1291 to make auto-updates go through

### CODE REVIEW

**Comment by hobinjk** [comment]
Updated for the merge of #1293. The 7.7.5-mp is because I messed up the first upload with the 7.7.5 version.

**Comment by nightpool** [comment]
lgtm.

I think in the future we should use the 7.7.5.1 if we need to upload a new version for non-code reasons, because the way firefox handles version strings here can be really confusing, and may not trigger an auto-update.

**Comment by nightpool** [comment]
@homu r+

**Comment by nightpool** [comment]
@homu r-

**Comment by nightpool** [comment]
Oh, shit, just noticed. Do we need to bump minVersion here? There area lot of people still on old versions of FF, and I don't want to strand them on older XKit versions if we can avoid it.

**Comment by hobinjk** [comment]
@nightpool minVersion is bumped from 35 to 51, which is when the WebExtension code landed (so I don't think the minVersion bump was necessary, but it is there)

**Comment by nightpool** [comment]
@hobinjk Let's remove the minVersion bump, because the addon we built has the old minVersion and I believe it's the correct one:

image

**Comment by hobinjk** [comment]
@nightpool Sounds good to me, updated commit accordingly

**Comment by nightpool** [comment]
LGTM @homu r+

**Pull request merged**
