### PR TITLE
Sound playback

### PR DESCRIPTION
**Pull request by Wolvan**
This is for #267
I also changed the description to indicate that it isn't supposed to be useful

### CODE REVIEW

**Comment by nightpool** [comment]
not super happy with hosting possibly-copyright-grey-area files on the github repo. maybe hotlink a tumblr-hosted clip instead?

**Comment by Wolvan** [comment]
Are you talking about the base64 encoded MP3?
We ain't going to get legal trouble due to fair use, but if you really want to be sure imma host it on tumblr real quick

**Comment by Wolvan** [comment]
There, it's a tumblr hosted MP3 instead of inline base64 now, @nightpool

**Comment by nightpool** [comment]
whether something qualifies as fair use or not is always a little
ill-defined at the best of times. Its also just a concern about whether we
need to be embedding an mp3 in the repo.

**Comment by Wolvan** [comment]
The reason I did embed the mp3 is because I thought we try to cut down on bandwith usage. But I guess a 4 second long mp3 isn't going to require much bandwith anyways, right?

**Comment by nightpool** [comment]
a) yes b) if someone has downloaded this extension, then they're probably
in for whatever bandwidth problems it comes with tbh.

**Comment by Wolvan** [comment]
true, true. I absolutely agree

**Comment by finagle29** [comment]
tested locally, LGTM @homu r+

**Pull request merged**
