### PR TITLE
Add Pokémon font to Pokés interfaces

### PR DESCRIPTION
**Pull request by ThePsionic**
*Warning*: The font won't work while testing this because the file hasn't actually been added to the repo yet. It's possible to test the font by changing the `src` in the `@font-face` at the top of the CSS file to `http://thepsionic.com/assets/fonts/pokepixelplus.ttf`. This requires unsafe sources to be loaded, however, since my website does not support HTTPS.

Adds a Pokémon-style pixel font to Pokés interfaces such as encountered Pokés and the list of caught Pokés. Some minor style changes had to be done to make it look a bit better (such as unbolding the (nick)name when clicked in the list). I also copied over the CSS from `.caught::after` to `.poke::after` to make the styles of the Pokémon on the dash and in the caught list match, and because the former looked better in general.

The font currently only supports basic Latin characters and punctuation, as well as the gender symbols we use for the Pokémon. It is a work in progress, and more characters may be added at a later point. It is hosted on [FontStruct](http://fontstruct.com/fontstructions/show/1227357/pokemon_pixel_plus), where you can clone the font, if you have an account, to work on it.

### CODE REVIEW

**Comment by ThePsionic** [comment]
Any spacing changes in the `.css` and `.js` files were done automatically by my IDE and should not pose a problem.

**Comment by Wolvan** [comment]
image
honestly, I do have kind of a hard time reading these with the new font

**Comment by Wolvan** [comment]
image
Should these also have the Pokémon font?

**Comment by Wolvan** [comment]
image
please give at least `é` a glyph

**Comment by Wolvan** [comment]
image
I think the position of the gender sign is wrong here

**Comment by ThePsionic** [comment]
`é` glyph has been added.
@Wolvan It most definitely is, I'll look into it and change the CSS if needed. I'll also add the font to the control panel interface.

**Comment by ThePsionic** [comment]
CSS positioning for the gender symbol has been fixed, and the control panel now also has the font.

**Comment by Wolvan** [comment]
LGTM, @homu r+

**Pull request merged**
