### PR TITLE
Escape special characters using en/decodeURIComponent

### LINKED ISSUE #1178: Safari storage breaks when encoding non-ascii characters
base64-encoding any non-ascii on safari, such as when saving it to storage, will cause a nasty error. This means some extensions can't be loaded on safari, some posts can't be archived, xcloud fails sometimes etc. etc.

I haven't checked recently to confirm this is still an issue, though I doubt it got fixed.

### PR DESCRIPTION
**Pull request by hobinjk**
Fixes #1178. This change requires a new Safari extension release.

### CODE REVIEW

**Comment by hobinjk** [comment]
important proof

**Comment by nightpool** [comment]
Looks good to me. Needs version bumps on the safari bridge version, right?

**Comment by hobinjk** [comment]
Who needs version bumps when you have 😎?
(pushed updated version with bumped Info.plist that also reflects Safari version 10.0 (12602.1.50.0.10))

**Comment by nightpool** [comment]
@homu r+

**Comment by nightpool** [comment]
@hobinjk Are we still waiting on signing this build? What's the status here?

**Comment by hobinjk** [comment]
@nightpool Yes, I don't know what Apple is doing with their lives but the gallery version is still 7.7.2 and I've received no review emails

**Comment by nightpool** [comment]
@hobinjk as far as I know, the "7.7.3" on the github releases page was actually 7.7.2 signed with new XCode. Did we update that release with this code? Should we make a new release in github just to avoid confusion?

**Comment by hobinjk** [comment]
Oh, I see now! The 7.7.3 release should be redone and changes need to be made to SafariUpdate.plist. I will update the 7.7.3 release and open a PR for the plist changes

**Pull request merged**
