### PR TITLE
Restore the follower count tweak

### PR DESCRIPTION
**Pull request by nightpool**
Restores the follower count tweak that was removed ages ago for being broken.

### CODE REVIEW

**Comment by blackjackkent** [comment]
Missing an addition to the destroy function, I believe. Unchecking doesn't put the number back. Otherwise LGTM.

**Comment by nightpool** [comment]
I used tweaks.add_css instead of tools.add_css, which is supposed to take care of it automatically. I noticed that too though, so not sure how to fix it.

**Comment by nightpool** [comment]
Yeah, it looks like we're not clearing `tweaks.css_to_add` properly. not sure when this changed or why

**Comment by blackjackkent** [comment]
Okay, we'll address that separately.

@homu r+

**Comment by bbigffoot** [comment]
F

**Comment by nightpool** [comment]
@bbigffoot ?

**Pull request merged**
