### PR TITLE
Blockquoted captions display properly in ER and RDO

### PR DESCRIPTION
**Pull request by dlmarquis**
This is what I was wordvomiting about on #605.

We were using the old parsing that didn't generate reply chains for blockquoted comments. This fixes that. The original purpose, to prevent blockquote generation when the previous person did not comment, also appears depricated.

### CODE REVIEW

**Comment by nightpool** [comment]
"Merge pull request #18 from new-xkit/master" ?

**Comment by nightpool** [comment]
I would like to check this against my local branch. I believe that this is all fixed there

**Comment by dlmarquis** [comment]
That commit is a product of Github's terrible web interface.

**Comment by nightpool** [comment]
@dlmarquis can you walk me through this change? As far as I can tell, this is designed so that we don't end up with a bunch of empty reblogs when we add the person you're reblogging this from to the chain.

**Comment by nightpool** [comment]
nevermind I get it now. integrated into my RDO pull

**Comment by nightpool** [comment]
this was integrated into RDO, so i'm removing the tag.

**Comment by nightpool** [comment]
r+, but I'm going to merge manually because of the conflicts.

**Comment by nightpool** [comment]
committed in c7f7814ce54b10ecf6b67e28c6b904342a103a2f

**Pull request closed without merging**
