### PR TITLE
Update dependencies; Use npm 5 package-lock.json

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by nightpool** [comment]
benefits of yarn:

 - easily diffable lock files
 - flat dependency tree (much smaller)
 - probably other stuff? it seems like a much better UX

**Comment by hobinjk** [comment]
I'm in favor of yarn in general and as a concept but I don't think it's better than npm in this situation.

In my opinion, the benefits of yarn are outweighed by having to tell potential contributors to install it if they have an issue. I'd rather have npm Just Work™️ so that someone can jump in with only the node/npm base installation. (the technicality here is that we could just amend the docs to include `npm install -g yarn` next to `npm install -g gulp`, but the Yarn install guide is adamant that using npm to install yarn is the worst decision possible)

I've flipped my opinion on this more times than I can count so tune in next week for @hobinjk talks about how yarn cures cancer while ending worldwide hunger

**Comment by MarkH817** [comment]
This PR might be okay to close since #1560 has added the `package-lock.json` file.

**Comment by hobinjk** [comment]
Yes, this is old and busted by now. Thanks for making updates happen!

**Pull request closed without merging**
