### PR TITLE
hide recommended adds global CSS to hide see more blogs and recommended posts

### PR DESCRIPTION
**Pull request by finagle29**
This exists because I really haven't conquered command line git and I couldn't rebase to fix conflicts in the last branch i tried to make these same changes in.  Let's try this again.

Improves upon #337 and #342

### CODE REVIEW

**Comment by Wolvan** [comment]
does the global CSS get removed in destroy yet?

**Comment by finagle29** [comment]
Yes, CSS added with `XKit.extensions.tweaks.add_css` is lumped together and then added with one `XKit.tools.add_css` which is removed in destroy

**Comment by Wolvan** [comment]
Ah alright then. LGTM
@homu r+

**Comment by finagle29** [comment]
@Wolvan I forgot to remove an old statement in the destroy routine can you check this again

**Comment by Wolvan** [comment]
This is why I dislike Github only showing me the changed areas

**Comment by Wolvan** [comment]
@homu r+

**Pull request merged**
