### PR TITLE
Migrate wiki into project

### LINKED ISSUE #635: Move documentation into main repo
Having the documentation over on the GitHub wiki is relatively low-friction for contributors, but I am of the opinion that including the documentation in the main project repo under `docs/` has a number of advantages:

- No need to use an external resource when developing locally
- The files in `docs/` would always reflect the information pertaining to whatever commit is currently checked out (ie. if you check out `aabbccd`, an API reference in `docs/` will reflect the API _at_ `aabbccd`, rather than the latest changes)
- We are not restricted to the flat file tree GitHub's wiki limits us to (ie. we can have proper concept grouping with folders)
- Should we no longer host the project on GitHub (or we want to mirror it somewhere else) the documentation is self-contained and can easily move with the project.

We should also [be able to retain the wiki history](https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories), should we care about that.

If we were to do this, I would also propose modifying the 'Home' page on the wiki to have a link to the `docs/` folder, and then lock the wiki to contributors only.

### PR DESCRIPTION
**Pull request by 0xazure**
Move wiki documentation into a project subfolder `docs/`.

Closes #635.

### CODE REVIEW

**Comment by 0xazure** [comment]
I would be open to discussion regarding the series of commits from the wiki repository history, given how many of them there are.

## Post-merge TODOs:

- [ ] Clean out wiki repository & redirect to `docs/` **OR** remove wiki entirely (via GitHub project settings)

**Comment by ThePsionic** [comment]
@0xazure Might be an idea to just squash it all under the header of "Merges wiki into main project"

**Comment by Wolvan** [comment]
I agree with @ThePsionic

**Comment by 0xazure** [comment]
I suppose the question would be if we care at all about the edit history of the wiki files.  There's a few more recent ones that should probably be kept in the history, like pretty much anything after new-xkit took over.

**Comment by ThePsionic** [comment]
I personally don't really care about the edit histories of the wiki.

**Comment by hobinjk** [comment]
I don't mind having the edit history available. It's nice to see who to blame for writing specific lines, especially if those lines appear to be wrong.

**Comment by nightpool** [comment]
- we should keep histories
 - they would show up in git log basically when they were created right? because default order is reverse chronological?
 - I'm down with removing the wiki altogether but we should make sure that the docs get into our gh-pages in rendered format somehow eventually.

**Comment by 0xazure** [comment]
> show up in git log basically when they were created

I believe so, yes.  They won't all get pushed to the top of the history if this is merged.

> make sure that the docs get into our gh-pages in rendered format somehow eventually

Not sure I follow with this.  @nightpool you mean you'd like to see all `docs/**/*.md` files added to `gh-pages` as HTML-rendered files?  I'm not sure I see the need for this, given that Markdown is pretty readable in its own right.  GitHub will also automatically render any pages you view in the web UI, so seeing HTML-formatted documentation pages would be as simple as viewing the `docs/` folder on GitHub.

**Comment by 0xazure** [comment]
@nightpool still waiting on a reply for the above.

**Comment by nightpool** [comment]
Must have totally missed that reply around the end of the term.

I'm fine to merge for now I was more thinking about long term stuff.

**Comment by 0xazure** [comment]
I see most of the documentation in this PR being eventually superseded by generated [JSDoc](http://usejsdoc.org/) documentation, which we would want to host through `gh-pages`.  This is more an effort to get the docs in sync with the project as a whole; we can evaluate how we want to handle new documentation on more recent pieces of the codebase separately.

**Comment by nightpool** [comment]
Yeah definitely. Didn't mean to confuse this pr with my long term
speculation.

**Comment by bvtsang** [comment]
LGTM, thank you very much!

@homu r+

**Pull request merged**
