### PR TITLE
Fixing "Delete Caption" feature of One-Click Postage

### PR DESCRIPTION
**Pull request by blackjackkent**
Had to update the object being sent to /svc/post/update.

(My first PR for this project, so definitely want another pair of eyes making sure I'm not doing anything dumb. ;) LMK! )

### CODE REVIEW

**Comment by blackjackkent** [comment]
Whoops...ignore the committer username mismatch please. >.> Forgot my local git was globally config-ed with info for my main github account.

**Comment by hobinjk** [comment]
For the change to actually be pushed to users the version number in the header of the extension needs to be increased. Otherwise, this looks great! Thank you for the contribution!

If you want to switch the commit author while making the version change, go ahead.

**Comment by blackjackkent** [comment]
Ah,  yes, good old push origin -f. Always forget o can do that for some reason. 

Updated with the version change. :)

**Comment by hobinjk** [comment]
Awesome! Merging now

**Pull request merged**
