### PR TITLE
Fix bolding links

### PR DESCRIPTION
**Pull request by nightpool**
This also resets the preference, since this tweak has been inactive for who-knows-how-long (ballpark 2 years) and literally no-one is going to remember that they had it enabled.

### CODE REVIEW

**Comment by Wolvan** [comment]
I really don't think fixing the proper destruction of a tweak isn't out of scope of a PR that is meant to fix a tweak, but I'd like some more opinions on that

**Comment by nightpool** [comment]
It's not "fixing the proper destruction of a tweak" it's "changing how and when destruction gets called for all tweaks". The tweak is properly destructed just like every other tweak, there's just something broken with cleaning up **all** tweak css (except those that use XKit.tools.add_css directly)

**Comment by Wolvan** [comment]
Then why are we not switching to XKit.tools.add_css to destroy this tweak?

**Comment by nightpool** [comment]
because moving ~30 tweaks over to a different function call is completely out of scope for this PR?

**Comment by Wolvan** [comment]
Start slowly. One tweak at a time. Or at least this tweak considering how we basically made a new one here. And since we made a new tweak we should properly handle all parts of it

**Comment by nightpool** [comment]
That's not even the right solution though, it doesn't have the same behavior as using add_to_css

**Comment by Wolvan** [comment]
Alright, you win. I checked through the thing and it's actually out of scope, considering the fix for it

**Pull request merged**
