### PR TITLE
Add gulp-cached to speed up linting

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by hobinjk** [comment]
@nightpool Happy birthday
@0xazure This seems like a pretty standard application of a pretty standard gulp tool. I also want to be able to use this on build:extensions, so whenever you are done with your refactor of it I will try to make it into a gulp-compatible streaming nonsense (or you can fold that into your changes)

**Comment by hobinjk** [comment]
Most importantly:
﻿[19:20:29] Starting 'lint:scripts'...
[19:20:42] Finished 'lint:scripts' after 13 s
[19:21:32] Starting 'lint:scripts'...
[19:21:33] Finished 'lint:scripts' after 435 ms
[19:21:47] Starting 'lint:scripts'...

**Comment by nightpool** [comment]
yessssssss

**Comment by 0xazure** [comment]
Lgtm. I haven't read up on the caching mechanisms gulp works with, but this is an easy change.

As far as extensions/themes building, I increasingly want to chunk that tool out into an entirely separate module. Something we'll have to think about.

@homu r+

**Comment by nightpool** [comment]
note @new-xkit/admin that you need to rerun npm install after we merged this pull.

**Comment by 0xazure** [comment]
Helps #298.

**Pull request merged**
