### PR TITLE
[ReplyViewer] Remove Extension

### PR DESCRIPTION
**Pull request by motackt**
ReplyViewer is now obsolete in React and non-React pages (#1794).

It has been superseded by Tumblr's Peepr function.

### CODE REVIEW

**Comment by motackt** [comment]
Correction: ReplyViewer has been superseded by Tumblr's notes popup that automatically shows replies.

**Comment by AprilSylph** [comment]
XKit Preferences will need a version bump

**Comment by motackt** [comment]
Oooooof course I forgot something XD

**Review by AprilSylph — APPROVED** [review]
this might be a little controversial if there's anyone left who uses their inbox and its peepr more than their dashboard, but given that ReplyViewer has no configuration, this could be reverted easily if need be

im not sure if ReplyViewer even works on legacy peepr though :thinking:

**Pull request merged**
