### PR TITLE
Further work around case sensitivity of getResponseHeader

### PR DESCRIPTION
**Pull request by hobinjk**
wake me up (wake me up inside)

### CODE REVIEW

**Comment by nightpool** [comment]
i'll have you know I laughed basically as loud as possible when I opened up this pull request

**Comment by nightpool** [comment]
we look for X-Tumblr-Kittens a **lot**. is this also affected?

**Comment by nightpool** [comment]
image

**Comment by hobinjk** [comment]
When things like that fail they leave XKit.interface.kitty.stored equal to "" which will mean that the next time a good law-abiding citizen tries to call XKit.interface.kitty.get() they'll request it from the server.

All of those places should be modified/updated in some way but they should not break the kitty

**Pull request merged**
