### PR TITLE
[WIP] Pokes

### PR DESCRIPTION
**Pull request by ThePsionic**
This extension that I started to build for shits and giggles got way out of hand. There's only one thing I can do with it now: finish it.

This extension randomly adds Pokémon to the dashboard, to the right of a post. You will be able to click on them in order to collect them. More functionality planned.

## To do:
- [x] Phase 1: Make random Pokémon show up on the dash
    - [x] TODO: Instead of serving over HTTP (http://pokeapi.co), serve over HTTPS
    - [x] Position the Pokémon properly, at the top of the post on the right side
    - [x] Fix darkening of post avatar when clicking the pokemon
    - [x] Use a self-hosted JSON file with Bulbapedia sprites
    - [x] Convert the Bulbapedia sprites to base64 in order to appease the bandwidth gods
- [x] Phase 2: Save ("catch") the Pokémon when clicked
    - [ ] Show them somewhere (CPanel, other kind of interface)
    - [x] Allow for having multiple of the same Pokémon
    - [x] Introduce genders using the canon M/F rates
        - [x] Save each gender separately
- [x] Phase 3: Add formes
- [x] ~~Phase 4: Give the Pokémon their types, in preparation of phase 5.~~ No longer needed.
- [x] ~~Phase 5: Add items, which can be found randomly like Pokémon~~ No longer needed since 99% of the items are evolutionary stones and evolutions aren't going to happen
- [x] ~~Phase 6: Evolutions~~ Decided against for my own sanity.
- [x] Phase 7: Pokémon rarity
    - [x] Use catch rate to determine the rarity of the Pokémon
- More?

### Current bugs and not-so-nice things
- [x] If a Pokémon appears at the top of the dash (before a second "page" load), the Pokémon cannot be clicked and does not get registered. Scrolling down the dash to load more content and scrolling back up solves this.
- [x] When creating notification popups, the names are not parsed. This leads to things like Pokémon-Variety as Pokémon name or a -male/-female prefix on gender-exclusive formes. For variety Pokémon this should look like Pokémon (Variety), and gender suffixes should be removed entirely.

### CODE REVIEW

**Comment by nightpool** [comment]
I'm down for merging when stage 1 and 2 are down. @ThePsionic do you want this merged earlier? 

also you guys might want to squash some amount of stuff as you go

**Comment by ThePsionic** [comment]
@nightpool I kinda don't want it pulled until it is entirely finished. If it would be pulled before everything has been implemented, it'd be easier to obtain the rarer Pokémon now and not having to do it when the rarity mechanics are actually in place. I also don't like to wipe progress, so that's why I made that decision.

I will definitely squash commits once phases end - phase 1 will be squashed into a single commit momentarily.

**Comment by nightpool** [comment]
Okay, no biggie. It'd be cool to get something out sooner rather then later
though. Maybe just disable the rare stuff until you have rarity?

**Comment by ThePsionic** [comment]
Few things to note at this time:
* There is no online version of the v2 database yet, and @nightpool suggested putting all needed data in the javascript file itself (excluding the sprites) in order to not eat data
* I kind of want to use the sprites from Bulbapedia ([example](http://bulbapedia.bulbagarden.net/wiki/File:325MS.png)) because 1) they are always 40x40 unresized -> no positioning fuckery because some Pokémon decide to be big and 2) sweet retro 8bit feel yo, but the direct links are made so that it's difficult to automatically fetch them. @nightpool also pointed out that `image-rendering: pixelated;` is a CSS property that resizes pixel art without making it blurry.

**Comment by Wolvan** [comment]
@ThePsionic wouldn't that absolutely bloat our extension file? Also, do you really want to manually copy all data?

**Comment by ThePsionic** [comment]
@Wolvan That's the main worry at the moment, yes, but it would definitely be nice to have a toned-down version of the database with just the stuff we need.

**Comment by Wolvan** [comment]
As in self-hosted or integrated?

**Comment by ThePsionic** [comment]
Either or. Probably requires some research to find out which is ultimately the best solution.

**Comment by ThePsionic** [comment]
### 29 october update
*Good things*
- The storage works! Pokémon are now saved when caught, with each gender saved separately.
*Bad things*
- There is a bug where, if a Pokémon appears at the top of the dash (before a second "page" load), the Pokémon cannot be clicked and does not get registered. Scrolling down the dash to load more content and scrolling back up solves this.
*Other things*
- Still need to make some sort of interface for checking which Pokémon are currently owned. Once that's done, the extension is good to be pulled as far as I know.

**Comment by Wolvan** [comment]
@ThePsionic I can take a look at the top most pokemon problem tomorrow

**Comment by ThePsionic** [comment]
### 30 october update
(midnight just rolled by for me)

*Good things*
- When catching a Pokémon, there is now a small notification popup that alerts the user to the Pokémon they caught, along with the gender of the Pokémon.

*Bad things*
- When creating the popups, the names are not parsed. This leads to things like Pokémon-Variety as Pokémon name or a -male/-female prefix on gender-exclusive formes. For variety Pokémon this should look like Pokémon (Variety), and gender suffixes should be removed entirely.

**Comment by ThePsionic** [comment]
@Wolvan It seems to happen randomly, sadly. I've seen it most consistently at the top of the dashboard, though.

**Comment by ThePsionic** [comment]
The database has been updated to include display names, which look a tad nicer on notifications.

**Comment by ThePsionic** [comment]
The database has been updated to serve images using base64 instead of DDoS-ing Bulbapedia.

**Comment by ThePsionic** [comment]
Changed the icon to
pokes

**Pull request closed without merging**
