### PR TITLE
XKit.interface.where(), XKit.api_key, removing === true

### PR DESCRIPTION
**Pull request by finagle29**
There are some weird regexes in older extensions and document.location.href checking that can be simplified by use of `XKit.interface.where()`.

I changed the individual api keys embedded in extensions to `XKit.api_key` for consistency, let me know if there’s something wrong with that.

### CODE REVIEW

**Comment by blackjackkent** [comment]
Looks like there's conflicts with master that are going to prevent this from merging. Can you rebase or resolve those conflicts?

**Comment by 0xazure** [comment]
There are a lot of unrelated changes in this one PR.  Maybe it's just a style thing on my part, but imo changes in a PR should be related somehow.

:-1: from me.  From a cursory glance the changes themselves look fine, but they should be separated out into separate PRs.

**Comment by finagle29** [comment]
@0xazure makes sense to separate the changes into separate PRs

**Comment by nightpool** [comment]
@finagle29 I think that because these extensions all have different API keys, they're all affected by different rate limits. something to keep in mind when changing them.

**Comment by finagle29** [comment]
I wasn't aware that there were rate limits for Tumblr's API and couldn't find any publicized, but that's a good reason to not have everything use the same API key.

**Comment by nightpool** [comment]
@finagle29 I might be mistaken. I thought I had seen something about it in the xkit source, but now going back I can't find anything related to it.

**Comment by finagle29** [comment]
@nightpool There's definitely rate limits for API calls, e.g. it looks like 60 calls per hour for /user/following (although it looks like maybe that is an error on Tumblr's part and should be 60 calls per minute) https://groups.google.com/d/msg/tumblr-api/DwFarwIqI7I/-uUL9AzkzyEJ Tumblr just hasn't included the limits in their API documentation (which is unfortunate)

**Pull request closed without merging**
