### PR TITLE
Serve local assets over HTTPS

### PR DESCRIPTION
**Pull request by 0xazure**
This modifies `gulp server` to serve local assets (built Extensions, etc) over HTTPS via self-signed certs.  Without this change, Tumblr on Chrome complains about:

>Mixed Content: The page at 'https://www.tumblr.com/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:31337/Extensions/dist/page/list.json'. This request has been blocked; the content must be served over HTTPS.

(there may be a similar issue on Firefox, I haven't tested this there).

I'll need a sanity check that this will also work on Firefox.  My steps to reproduce are:

1. Checkout this branch
1. `npm install`
1. Modify [this line](https://github.com/new-xkit/XKit/blob/715339c0a2b758dd78e7e9b51895ce4cc64c3acb/xkit.js#L233) in `xkit.js` to point it to `//:localhost:31337/Extensions/dist/`
1. Load up Tumblr in the browser
1. XKit > Other > 'Update all my extensions' and ensure that the extensions actually update from `localhost` (may need to pop open network tools to verify)

---

TODO:

- [ ] Update [Build XKit](https://github.com/new-xkit/XKit/wiki/Build-XKit) with documentation about `gulp server`.

### CODE REVIEW

**Comment by 0xazure** [comment]
@hobinjk would appreciate your feedback on this.  Particularly around including those dev certs.

**Comment by nightpool** [comment]
@0xazure can't the gulpfile generate devcerts on demand? (i.e. generate
them once and re-use the same ones..)

**Comment by 0xazure** [comment]
I could _possibly_ wrangle an auto-generation feature, assuming guaranteed access to an `openssl` bin.  But given that `openssl` isn't available everywhere (particularly on Windows), I think including the certificate files is a better bet.

**Comment by nightpool** [comment]
fair. still seems weird to keep it in tree though.

**Comment by hobinjk** [comment]
@0xazure Firefox rejects the certificate:
>localhost:31337 uses an invalid security certificate.
>
>The certificate is not trusted because it is self-signed.
>The certificate is only valid for New XKit

**Comment by 0xazure** [comment]
Iiiinteresting.  Thank you, I'll follow up on that.

**Comment by hobinjk** [comment]
It works if you manually visit localhost:31337 and add a security exception

**Comment by nightpool** [comment]
also this didn't work for me on chrome initially, I had to do something
similar. (go to localhost:31337 and click "continue anyway"

**Comment by 0xazure** [comment]
Unfortunately I don't think there's much of a 'fix' for the initial self-signed cert rejection.  I'm really not comfortable recommending [adding the certs to the browser cert store](http://stackoverflow.com/a/15076602) because these certs are public.

I've added some logging to `gulp server` to remind devs to create a security exception on their own, but haven't been able to think of any other solutions.  Thoughts?

**Comment by nightpool** [comment]
adding the initial warning is good enough for me!

**Comment by 0xazure** [comment]
TODO:

- [ ] Update [Build XKit](https://github.com/new-xkit/XKit/wiki/Build-XKit) with documentation about `gulp server`.

**Comment by hobinjk** [comment]
LGTM
@homu r+

**Pull request merged**
