### PR TITLE
Fixing behavior of Serif font on post bodies

### LINKED ISSUE #300: accesskit doesn't change font to serif
from ask box:
>AccessKit's changing of the font to Serif isn't working (on Chrome).

unconfirmed.

### PR DESCRIPTION
**Pull request by blackjackkent**
Fixes #300

### CODE REVIEW

**Comment by nightpool** [comment]
caution in that this will probably cause a bunch of users to be stuck with broken config options. (where they have sans-serif in their storage but there's no value with that id existing). 

seems like we should either leave that change out for now or write some sort of migration logic. no?

**Comment by blackjackkent** [comment]
Oh, that's a good point. Me bein' overeager. >.< Undid that part of the change and repushed.

**Comment by nightpool** [comment]
Looks great

@homu r+

**Comment by nightpool** [comment]
In the future you can probably squash small commits like these.

**Pull request merged**
