### PR TITLE
Add "Hide Avatar" icon

### PR DESCRIPTION
**Pull request by ThePsionic**
img

### CODE REVIEW

**Comment by ThePsionic** [comment]
Liked this one a bit better
img

**Comment by ThePsionic** [comment]
(sidenote: i am in no way a graphical designer)

**Comment by ThePsionic** [comment]
actually nah the first one is better

**Comment by ThePsionic** [comment]
img
Now with more gradient

**Comment by dlmarquis** [comment]
@homu r+, I'm digging the serial killer feel you've got going on

**Comment by hobinjk** [comment]
@homu r=dlmarquis
Looks like the comma confused the bot

**Pull request merged**
