### PR TITLE
changes slim blockquotes style to match tumblr's

### LINKED ISSUE #223: slim block quotes broken
slim block quotes is a little broken style-wise:  
image
this is what blockquotes normally look like:
image

we should make sure the border is just as thin, and remove the left padding. I'm guessing tumblr updated their styles and atesh didn't.

### PR DESCRIPTION
**Pull request by finagle29**
finagle29 v. command line git round 2

fixes #223

### CODE REVIEW

**Comment by blackjackkent** [comment]
Spiffy. :) LGTM

@homu r+

**Comment by blackjackkent** [comment]
Ack -- realized after I approved that you didn't bump the version number. Can you put in another PR for that?

**Comment by nightpool** [comment]
@finagle29 @blackjackkent I'll do it manually, don't worry about it

**Comment by blackjackkent** [comment]
:+1:

**Pull request merged**
