### PR TITLE
RDO: highlight alternating reblogs option (flat)

### PR DESCRIPTION
**Pull request by lizzledpink**

### CODE REVIEW

**Comment by nightpool** [comment]
Uh oh—might want to check out your git history

**Comment by lizzledpink** [comment]
I'm not sure what you're saying but ftr all those commits except the last one are just me accidentally reverting the wrong things and then fixing that

**Comment by nightpool** [comment]
Yeah, so they should be removed from the history/rebased away no? We don't
want any non-pr merge commits cluttering up our repo.

**Comment by lizzledpink** [comment]
Makes sense. I'm not entirely sure how; I'll try to figure out how to do that.

**Comment by bvtsang** [comment]
To clean up your commit history in this branch, you might want to look into [interactive rebasing](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages). Here's [a tutorial](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) that might help.

**Comment by lizzledpink** [comment]
Thanks for the link. Tried it and I think I succeeded in rebasing all but one commit? Having trouble getting that last one for some reason.

**Comment by nightpool** [comment]
you seem to have added more commits? 

image

r+ me, I'll just merge the change manually.

**Comment by bvtsang** [comment]
There's now 11 commits in this branch. There should only be one.

Let's say that I just ran `git rebase -i HEAD~11`. Here's the text I see:

```
pick a6a1044 Update classic_header.js
pick d5a524a Add scrolling header & menu logout button to mobile
pick 7bc8492 Mobile coding is hard guise
pick 4e2a524 I am not Atesh
pick a9c1eb3 Spelling
pick 318945e Fixed if statements
pick 206342f Make click on Tumblr Logo Soft-refresh again
pick ef238d1 Fix limit people in peepr
pick 770b647 Fix for #807
pick a0839e5 Forgot to change the version number
pick fe6ce98 Deprecate `XKit.lang`
pick e5b110f Create Pokes Extension
pick 99e2b15 Pokés: Made Cosplay Pikachu all-female
pick 26350be Clicked notifications link to Bulbapedia page
pick 2398d30 Fixed variable definitions and version number
pick 6f33098 Optional backgrounds for Pokemon
pick 1faa909 Removing line break
pick 25a0e18 RDO: Add reverse rainbow scheme
pick 928b504 Adding option to remove usernames from messages

# Rebase c323aac..0930126 onto c323aac
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

In this example, pretend the commit you want to keep is "RDO: Add reverse rainbow scheme". The result of your rebase should look like this:

```
pick 25a0e18 RDO: Add reverse rainbow scheme

# Rebase c323aac..0930126 onto c323aac
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Try to rebase _only_ over the new commits in your branch (starting with "Add option for background colors for reblogs"). You can control the range by changing the number after  `HEAD~11`.

After you're done rebasing, you'll need to `git push -f` to overwrite the 11 commits on Github with your ideal single commit.

I hope this helps.

**Comment by lizzledpink** [comment]
Ah... That's... completely different from how the guide suggested it worked. And also makes far more sense than it. Thank you.

**Comment by bvtsang** [comment]
In retrospect, I should've linked directly to the [Reordering Commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Reordering-Commits) heading of the Git guide. My apologies.

**Comment by lizzledpink** [comment]
Thanks @nightpool!

**Pull request closed without merging**
