### PR TITLE
Teeny tiny grammar change

### PR DESCRIPTION
**Pull request by wintergone**

### CODE REVIEW

**Comment by Wolvan** [comment]
Change the version and you're golden!

**Comment by wintergone** [comment]
Like that?

**Comment by Wolvan** [comment]
Bingo.
@homu r+

**Comment by Wolvan** [comment]
there you go, merged and available as an update in a minute or two

**Comment by wintergone** [comment]
Easier than I thought it would be. May be around to make other minuscule picky changes in the future :grin:

**Comment by Wolvan** [comment]
We are very much OK with that. If you want to know more about developement, you can always join our gitter

**Pull request merged**
